### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [greg7mdp/parallel-hashmap#1]
I would like to point out that an identifier like “[`__v`](https://github.com/greg7mdp/parallel-hashmap/blob/d5bad0bb45944ec7ccab11dc92665e98f028e2ef/parallel_hashmap/phmap.h#L90 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by greg7mdp** [comment]
Done, thanks for reporting the issue!

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/greg7mdp/parallel-hashmap/commit/0c53c040fda55f683bcc1eec9f5690b8062d1376 "Renaming of variable names").

**Comment by greg7mdp** [comment]
No problem. How did you notice this so quickly. Are you using a tool?

**Comment by elfring** [comment]
Would you like to try the GitHub search interface out for such a source code review?
