### ISSUE TITLE
`has_hash_value` does not work as expected

### ISSUE THREAD

**Issue by Tuj3Bz90dV** [greg7mdp/parallel-hashmap#10]
The Visual Studio 2017/2019 STL exports the template function 
```
template <class _Kty>
inline size_t hash_value(const _Kty& _Keyval) { // hash _Keyval to size_t value one-to-one
  return (size_t) _Keyval ^ (size_t) 0xdeadbeef;
}
```
into the `std` namespace. This causes `has_hash_value` to always return `true`, seeing that the function is well-defined for any type as long as we don't have to actually run it.

This causes an unfortunate interaction with the `StringHash` class, which is instantiated unconditionally as soon as you include `phmap.h` and C++17 is being used:
```
template <class T>
struct Hash
{
    template <class U, typename std::enable_if<has_hash_value<U>::value, int>::type = 0>
    size_t _hash(const T& val) const
    {
        return hash_value(val);
    }
 
    template <class U, typename std::enable_if<!has_hash_value<U>::value, int>::type = 0>
    size_t _hash(const T& val) const
    {
        return std::hash<T>()(val);
    }
 
    inline size_t operator()(const T& val) const
    {
        return _hash<T>(val);
    }
};
// ...
struct StringHash 
{
    using is_transparent = void;

    size_t operator()(std::string_view v) const {
        return phmap::Hash<std::string_view>{}(v);
    }
};
```

This will try to instantiate the above `std::hash_value` on `std::string_view` and fail miserably. One workaround is to define `hash_value(std::string_view)` somewhere.

**Comment by greg7mdp** [comment]
Thank you for that great bug report. I'll look into it later today. You probably have a `using namespace std;` somewhere, right?

**Comment by greg7mdp** [comment]
Issue is fixed, thanks again for reporting it. Please don't hesitate to let me know if you have any issue or suggestion for phmap, I'ma always happy to get feedback.
