### ISSUE TITLE
Cmake target_link_library failes with phmap

### ISSUE THREAD

**Issue by DariuszSabala** [greg7mdp/parallel-hashmap#100]
Hi

I just checkouted parallel-hashmap as submodule, added it to build system with

`add_subdirectory(parallel-hashmap)`

and tried to use phmap in one of my libraries using

`target_link_library(PRIVATE phmap)`

I have errors like this during configuring cmake build:

`"  Cannot find source file:
    /home/user/Projects/ProjectName/third-party/parallel-hashmap/phmap.h"`

I think it my be related to the way this project cmake script handles sources (ie. header files)

https://github.com/greg7mdp/parallel-hashmap/blob/master/CMakeLists.txt#L13

They are used in target_sources https://github.com/greg7mdp/parallel-hashmap/blob/master/CMakeLists.txt#L13
directly without "parallel_hashmap" folder in path.

I am quite novice with cmake but I added plenty of libs to my project this way (add_subdirectory and target_link_libraries)and every library works, for example magic_enum library...

Could you give me a hint what I am doing wrong?

**Comment by greg7mdp** [comment]
How do you include `phmap.h` in your C++ file. Do you use `#include <parallel_hashmap/phmap.h>`?

**Comment by DariuszSabala** [comment]
Yes, exactly like this, even with same bracket type due to guidelines. But even when I do not include phmap.h in any of my files and only add phmap to target_link_library I have an error on cmake configuration phase.

**Comment by greg7mdp** [comment]
Hi Darius, I'm sorry I am far from a cmake expert myself.
If you make the following change, does it solve the problem?
![image](https://user-images.githubusercontent.com/1496907/119499486-c40bf880-bd34-11eb-998a-0b5daedad3b1.png)

**Comment by greg7mdp** [comment]
Actually, probably this would work:
![image](https://user-images.githubusercontent.com/1496907/119501752-28c85280-bd37-11eb-8dbe-287c7ea73617.png)

**Comment by DariuszSabala** [comment]
First solution didnt helped, second one didn't helped to due to lack of CMakeLists.txt file inside parallel_hashmap folder, what helped me was this: 
![image](https://user-images.githubusercontent.com/73875238/119647297-648b1700-be20-11eb-9162-7f74b123b543.png)

**Comment by greg7mdp** [comment]
Thanks @DariuszSabala I added your change. I do appreciate the help!
