### ISSUE TITLE
im using vs2019

### ISSUE THREAD

**Issue by ActivePeter** [greg7mdp/parallel-hashmap#101]
![image](https://user-images.githubusercontent.com/8100696/120368308-7ef35200-c344-11eb-86e6-713d1b1669b0.png)
It shows error C2064 after I compiled.
My system is windows 10.
My development tool is vs2019

**Comment by greg7mdp** [comment]
Do you have an example program?

**Comment by ActivePeter** [comment]
> Do you have an example program?

[https://github.com/ActivePeter/GAMES101_study](https://github.com/ActivePeter/GAMES101_study)    in the patest folder.

**Comment by ActivePeter** [comment]
I found out that Im using a struct as a key, and it need hash func.
