### ISSUE TITLE
Optimize for big array of hash sets of varying sizes

### ISSUE THREAD

**Issue by Char-Aznable** [greg7mdp/parallel-hashmap#102]
Hi, thank you for this excellent implementation of hash map. I have an application where I have on the order of 100 million sparse binary matrices that need to be kept in an array. I frequently need to do weighted sums over the matrices. Each matrix can be represented as an instance of `parallel_flat_hash_set`. I am wondering if the obvious way of using an array of `parallel_flat_hash_set` is the best way to go, considering that the number of non-zero elements of these matrices vary a lot. I doubt in my application it would ever hit the memory limit of my machine to but in case it did, would there be an easy way to save memory for making such a big array of such hash sets? Thanks!

**Comment by greg7mdp** [comment]
Hi @Char-Aznable,

Thanks for the kind words. I think in your case, because you have many matrices, but each matrix is probably not requiring a lot of memory, it would be better to store each matrix in a `flat_hash_set`. This would seem pretty optimal to me. Maybe if you have some implementation sample you can share I would be able to understand better your use case and make other suggestions.

**Comment by Char-Aznable** [comment]
Hi @greg7mdp , thanks for your suggestion. Here's a scaled-down version of what I actually do:
```c++
#include <string>
#include <vector>
#include <random>
#include <parallel_hashmap/phmap.h>
#include <parallel_hashmap/phmap_utils.h>

struct Key {
  uint32_t k_[2];

  bool operator==(const Key& rhs) const {
    return rhs.k_[0] == k_[0] && rhs.k_[1] == k_[1];
  }
};

namespace std {

template<> struct hash<Key>
{
  std::size_t operator()(const Key& key) const
  {
    return phmap::HashState().combine(0, key.k_[0], key.k_[1]);
  }
};

};

using Set = phmap::flat_hash_set<Key>;

static constexpr uint32_t nRows = 100;
static constexpr uint32_t nPairsMax = nRows * 3;
static constexpr uint32_t nPairsMin = 0;

int main(int argc, char* argv[]) {

  int iArg = 1;
  const uint32_t nMatrices = std::stoul(argv[iArg++]);

  std::vector<Set> vs;


  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<uint32_t> distrib(nPairsMin, nPairsMax);

  for(int iMatrix = 0; iMatrix < nMatrices; ++iMatrix) {
    //Emulate some complicated process of generating the hash map by:
    //1) determine the number of valid keys
    const uint32_t nPairs = distrib(gen);
    //Then store the keys
    vs.push_back(Set{});
    for(uint32_t iKey = 0; iKey < nPairs; ++iKey) {
      vs.back().insert(Key{iKey, iKey});
    }
  }

}

```
I manage to extrapolate the peak memory consumption to about 240 GB at `nMatrices = 1e8`. Considering that in my real usage case, `nPairsMax` (the maximal number of of keys in all matrices) is a few times higher than what is shown in the code above, I'd love to hear your suggestion on how to save some extra space in this scenario if possible. I know the memory consumption is already close to the theoretical size (~223 GB) for keeping that many number of `uint32_t` pairs so I wouldn't push too hard on this unless it's trivial to do so. Thanks for looking at this anyway!

**Comment by greg7mdp** [comment]
This seems pretty optimal to me. Of course in this example you always insert the same keys in all matrices, but I assume that in the real app it is not the case and that the keys are somewhat random. I wonder what these matrices are used for though?

**Comment by Char-Aznable** [comment]
Yes, yhe keys will be random in the real use case. The tasks are like: tally the number of matrices which have keys (i, j), (k,l), ...; weighted sum of all the matrices, where the weights are updated on the fly

**Comment by greg7mdp** [comment]
What is the range of values that your matrices can have for i, j, k, l? Can these be any uint32_t integer?

**Comment by Char-Aznable** [comment]
The keys in general will be in the range [0, nRows), where nRows can be any where betweem 10000 and 1000000 so I can not make that assumption

**Comment by greg7mdp** [comment]
I can't think of a way to improve what you have then!

**Comment by Char-Aznable** [comment]
Thanks for looking into this anyway!
