### ISSUE TITLE
btree question

### ISSUE THREAD

**Issue by jmbnyc** [greg7mdp/parallel-hashmap#103]
Greg,

I have a quick question for you. I want to use btree_set with a special 16 byte composite key where the the key is really two keys (think of it as hi and lo u64 parts of a u128). I then want to use lower_bound and upper_bound to find the range for given hi value, e.g lower will use (key, 0UL) and upper will use (key, ~0UL). When reviewing the btree, I see that upper and lower bound can use linear or binary search. However, I think if I provide a custom "less" then it will use linear search unless I derive from the compare tag object. Is that correct? Also, what I really want to lower, upper bound plus the count of the items. I assume that the best idea here might to be get lower bound and the walk until getting to upper bound so that the walk produces the count. Any thoughts?

Thanks in advance ,
/JMB

**Comment by greg7mdp** [comment]
can't you just use uint128_t as a key? Then the default comparison function would be fine, and you can use `btree_set::lower_bound` and `btree_set::upper_bound` to find iterators bound the range of all keys matching (key, xxx).

> plus the count of the items. I assume that the best idea here might to be get lower bound and the walk until getting to upper bound so that the walk produces the count.

yes I think that's right.

Another way to store these would be `btree_map<uint64_t, btree_set<uint64_t>>` which would make getting the count faster since the btree_set internally keeps track of its size.

**Comment by jmbnyc** [comment]
Greg,

Thanks for your response.

Well, I don't want to use two level map --> set because I need to minimize memory as I need to store up to 1B of these composite keys, e.g. that is why I want to use a single set combined with lower_bound/upper_bound.

Assume that I don't want to rely on native 128 bit support and thus will have my own class for the composite key. Thus, how do I get the btree code to use binary search when doing lower_bound? Do I just need to derive the compare class from the tag class and support the appropriate compare function?

**Comment by greg7mdp** [comment]
> Well, I don't want to use two level map --> set because I need to minimize memory as I need to store up to 1B of these composite keys
I would try it, I'm not convinced the memory usage would be significantly higher.
> Thus, how do I get the btree code to use binary search when doing lower_bound?
I don't think you should worry about that, this is just for the search on one node because one node stores multiple keys in a btree.

**Comment by jmbnyc** [comment]
The memory usage is much larger because of the 1B items in the "set", I can have a significant number that might have a item which means a huge number of btree_set objects with 1 item and that is at least 256 bytes whereas my scheme it would only be 16 bytes. Imagine a scenario where 500M of the hi part of the key refer to exactly one entry in the set but the other 500M all share the same hi part. In this scenario, the memory usage for a single set with 16 byte composite key will be far less than map of sets.

Oh, I get it, you are saying that the linear vs binary search only applies to array of items inside a node, correct? In that case, then yes, I should not worry about it esp for integer compare.

**Comment by greg7mdp** [comment]
You are right. I had assumed a somewhat random distribution.

> linear vs binary search only applies to array of items inside a node, correct? 

yes, exactly!

**Comment by jmbnyc** [comment]
Thanks again for you time.
