### ISSUE TITLE
std::shared_mutex support

### ISSUE THREAD

**Issue by SX91** [greg7mdp/parallel-hashmap#11]
Hello!

Is std::shared_mutex support for C++14 and higher planned? I know I can provide LockableImpl specialization for it, but what about native support?

**Comment by greg7mdp** [comment]
Sure, will do. `std::shared_mutex` is C++17 but you are right it would be good to have.

**Comment by SX91** [comment]
I'd also like to ask what operations are exactly protected by mutex? It seems like only tables themselves are protected, not the values nor iterators returned from `emplace`/`insert`/`find`.

**Comment by greg7mdp** [comment]
Hi @SX91 , I just added native support for std::shared_mutex.

**Comment by greg7mdp** [comment]
> It seems like only tables themselves are protected, not the values nor
iterators returned from emplace/insert/find 
 
yes, that is correct. Arguably this is an issue. which means that you have
to be careful to use only some APIs when relying in internal table locking.
Maybe I should just remove this internal locking alltogether?
 
Thanks,
 
greg

  _____
