### ISSUE TITLE
Possible missing lock?

### ISSUE THREAD

**Issue by amitma1** [greg7mdp/parallel-hashmap#112]
Hi!
So I've been looking around the code to try and implement locked `for_each()` on the `parallel_flat_hash_map`, and I ran across this line, now I'm not 100% into the code so I might be missing out here, but it seems like a construction of `shared_lock` without a mutex, which in fact won't lock anything.

Am I missing something?

https://github.com/greg7mdp/parallel-hashmap/blob/e9cc706a9743fdc1a5545ff44d1fa46f347b677b/parallel_hashmap/phmap.h#L3255-L3263

Regards :)

**Comment by amitma1** [comment]
Nevermind, I missed the fact it's populated inside the function call :P

**Comment by greg7mdp** [comment]
Just curious, why do you need this?

**Comment by amitma1** [comment]
We have 2 big maps that have multiple threads updating and reading data from,
In some cases a thread can insert data that will never be used, hence will never be removed.
For that we have a scheduled job, that cleans up unused keys after a period of time, and to do that we need to iterate over all the keys in the map.

In the current solution, it gets a little ugly, because we can't use regular iterators because of thread safety,
And our only option is to keep another container, that does the book keeping of the keys, and is locked as a whole (so we could iterate over it safely).
This introduces unnecessary memory footprint, and an additional overhead of locking over an entire container.

I tried doing it using inheritance, but it wasn't really possible :(
I was thinking about `for_each` that holds a shared lock per submap, while iterating over it.
