### ISSUE TITLE
serialize.cc example doesn't seem to work with cereal

### ISSUE THREAD

**Issue by Markusjsommer** [greg7mdp/parallel-hashmap#116]
I'm trying to save/load a flat_hash_map with non-trivially-copyable stuff using cereal. It fails to compile due to a static assert: "cereal found more than one compatible input serialization function for the provided type and archive combination." Tried cereal v.1.3.0 and the latest github cereal commit, and both result in the same error.  I can comment out the static assert to compile successfully, but the table can't seem to actually load at runtime. Any help would be greatly appreciated!

Changing "#define USE_CEREAL 0" to 1 in the serialize.cc example results in the same error, see below:

chris@mba parallel-hashmap % g++ -std=c++14 -I/Users/chris/Downloads/parallel-hashmap -I/Users/chris/Downloads/cereal/include examples/serialize.cc
In file included from examples/serialize.cc:9:
In file included from /Users/chris/Downloads/cereal/include/cereal/types/unordered_map.hpp:33:
In file included from /Users/chris/Downloads/cereal/include/cereal/types/concepts/pair_associative_container.hpp:34:
/Users/chris/Downloads/cereal/include/cereal/cereal.hpp:995:9: error: static_assert failed due to requirement 'traits::detail::count_input_serializers<phmap::flat_hash_map<unsigned int, int, phmap::Hash<unsigned int>, phmap::EqualTo<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, int>>>, cereal::BinaryInputArchive>::value < 2' "cereal found more than one compatible input serialization function for the provided type and archive combination. \n\n Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair (you may not mix these). \n Use specialization (see access.hpp) if you need to disambiguate between serialize vs load/save functions.  \n Note that serialization functions can be inherited which may lead to the aforementioned ambiguities. \n In addition, you may not mix versioned with non-versioned serialization functions. \n\n "
        static_assert(traits::detail::count_input_serializers<T, ArchiveType>::value < 2,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chris/Downloads/cereal/include/cereal/cereal.hpp:853:15: note: in instantiation of function template specialization 'cereal::InputArchive<cereal::BinaryInputArchive, 1>::processImpl<phmap::flat_hash_map<unsigned int, int, phmap::Hash<uint32_t>, phmap::EqualTo<unsigned int>>, 0>' requested here
        self->processImpl( head );
              ^
/Users/chris/Downloads/cereal/include/cereal/cereal.hpp:730:9: note: in instantiation of function template specialization 'cereal::InputArchive<cereal::BinaryInputArchive, 1>::process<phmap::flat_hash_map<unsigned int, int, phmap::Hash<uint32_t>, phmap::EqualTo<unsigned int>> &>' requested here
        process( std::forward<Types>( args )... );
        ^
examples/serialize.cc:113:23: note: in instantiation of function template specialization 'cereal::InputArchive<cereal::BinaryInputArchive, 1>::operator()<phmap::flat_hash_map<unsigned int, int, phmap::Hash<uint32_t>, phmap::EqualTo<unsigned int>> &>' requested here
            archive_in(table_in);             // deserialize from file out.cereal into table_in
                      ^
1 error generated.

**Comment by greg7mdp** [comment]
Thank you @Markusjsommer for reporting the issue.
This was because phmap has a dump() function and cereal doesn't like this.
I have added a change, so just define PHMAP_DISABLE_DUMP on the command line or in your file before including phmap.h and that should fix it.
Also the example works again now.
