### ISSUE TITLE
insert in parallel problem

### ISSUE THREAD

**Issue by kanonka** [greg7mdp/parallel-hashmap#118]
Hi, I'm using your hash map to write data to it in parallel.
Here is the function that is being called in parallel (using concurrency lib on Windows, c++, VS2019):

// class member:
phmap::parallel_flat_hash_map<SimpleString, int, phmap::priv::hash_default_hash<SimpleString>, \
	phmap::priv::hash_default_eq<SimpleString>, \
	std::allocator<std::pair<const SimpleString, int>>, 8, srwlock>			m_stringsMap;

// class func:

int addParallel(const SimpleString& str, volatile long* curIdx)
    {
        int newIndex = -1;

        auto inserted = m_stringsMap.insert(std::make_pair(str, newIndex));
        if (inserted.second) // we are the first to insert
        {
            newIndex = InterlockedIncrement(curIdx);
            m_stringsMap[str] = newIndex;
        }
        else // we are NOT first - someone already inserted the pair
        {
            while (newIndex < 0)
            {
                ::SwitchToThread();
                newIndex = m_stringsMap[str]; // 
            }
        }
        
        return newIndex;
    }

My assumption is that insert behaves same way as concurrency::concurrent_unordered_map:
1. If this thread was the one that inserted the key, it can safely modify the value for it, since only this thread will have inserted.second set to true.
2. if other thread already inserted that key (and doesn't matter what is the value for that key is!), then inserted.second is false, and all that we need to do is to read from it until the value is modified to be something other than -1 (curIdx starts with 0).

Most of the time, this works. But occasionally, it goes into forever loop in that while loop. This can happen, as I  understand, in the following cases:
- either thread that actually inserted the key received inserted.second as false; OR
-  newIndex = m_stringsMap[str] keeps reading initially inserted value instead of reading the updated value.

Similar logic works flawlessly with concurrency::concurrent_unordered_map.
I really wanted to use your map, since it's faster almost twice than concurrency::concurrent_unordered_map; but this bug stops me from using it. Can you please take a look?

**Comment by greg7mdp** [comment]
Hum, sure I'd like to help. How is `srwlock` defined?

**Comment by greg7mdp** [comment]
Did you use:
```
        class srwlock {
            SRWLOCK _lock;
        public:
            srwlock()     { InitializeSRWLock(&_lock); }
            void lock()   { AcquireSRWLockExclusive(&_lock); }
            void unlock() { ReleaseSRWLockExclusive(&_lock); }
        };
```

If so, just out of curiosity, can you try `std::mutex` instead?

**Comment by greg7mdp** [comment]
Or maybe try this (this is a phmap extension API). Hopefully it compiles I didn't try it.

```
using Map = phmap::parallel_flat_hash_map<SimpleString, int, phmap::priv::hash_default_hash, 
                                          phmap::priv::hash_default_eq, 
                                          std::allocator<std::pair<const SimpleString, int>>, 8, srwlock>;
Map  m_stringsMap;

// class func:
int addParallel(const SimpleString& str, volatile long* curIdx)
{
    int newIndex = -1;

    m_stringsMap.lazy_emplace_l(str,
                                [&](int& v) { newIndex = v; },   // called only when key was already present
                                [&](const Map::constructor& ctor) { newIndex = InterlockedIncrement(curIdx); ctor(str, newIndex); }); // construct value_type in place when key not present
    return newIndex;
}
```

**Comment by kanonka** [comment]
Yes, I tried exactly that srwlock, as well as std::mutex - same result.

Let me try that lazy_emplace_l. I will let you know the outcome.

**Comment by kanonka** [comment]
OK, this extension API worked perfectly, except it is slightly slower than the original code (~1700ms vs ~1500ms), but still much faster than concurrent_unordered_map (~3580ms).

By the way, is there any way to speed up the clean/destruction? Having only ~6mln pairs of (string,int) takes over 2000ms to destroy.

**Comment by greg7mdp** [comment]
> OK, this extension API worked perfectly, except it is slightly slower than the original code (~1700ms vs ~1500ms), but still much faster than concurrent_unordered_map (~3580ms).

I'm surprised it is slower. Did you use it as in my answer (without the `while` and the `::SwitchToThread();`)? It should be faster I think.

> By the way, is there any way to speed up the clean/destruction? Having only ~6mln pairs of (string,int) takes over 2000ms to destroy.

It is probably the destructor of `SimpleString` that takes most of the time. Maybe freeing memory? What is `SimpleString`? How long are the strings you store?

**Comment by kanonka** [comment]
I used your answer verbatim, i.e. as is - no while and the ::SwitchToThread().

SimpleString is just a typedef for std::string in this case.
I will doublecheck, but don't think std::string destructor is a culprit in this case. Before adding this map I had two vectors of strings (i.e. double number of std::string instances), and their destruction was basically immediate. Once I added the map it started to take quite some time to destruct - about same time as concurrent_unordered_map. I will investigate more.

**Comment by kanonka** [comment]
OK, just did performance profiling. Same number of same values in the std::unordered_map is being destroyed almost immediately (~100ms or less). Using phmap profiler shows culprit at PolicyTraits::destroy(&alloc_ref(), slots_ + i) in this function:

    void destroy_slots() {
        if (!capacity_) return;
        for (size_t i = 0; i != capacity_; ++i) {
            if (IsFull(ctrl_[i])) {
                PolicyTraits::destroy(&alloc_ref(), slots_ + i);
            }
        }
        auto layout = MakeLayout(capacity_);
        // Unpoison before returning the memory to the allocator.
        SanitizerUnpoisonMemoryRegion(slots_, sizeof(slot_type) * capacity_);
        Deallocate<Layout::Alignment()>(&alloc_ref(), ctrl_, layout.AllocSize());
        ctrl_ = EmptyGroup();
        slots_ = nullptr;
        size_ = 0;
        capacity_ = 0;
        growth_left() = 0;
    }

**Comment by greg7mdp** [comment]
Yeah! Happy phmap is working out for you! 

As for the issue with the original code, you are right it is a bit worrisome, but I don't see what the issue could be just from reading the code and I don't have a full sample.

**Comment by greg7mdp** [comment]
Just curious, what is the average length of the strings you insert?

**Comment by kanonka** [comment]
> Just curious, what is the average length of the strings you insert?

About 21 symbols.

**Comment by greg7mdp** [comment]
You can probably make the destruction almost instantaneous by using an arena allocator for the strings: https://developers.google.com/protocol-buffers/docs/reference/arenas

**Comment by kanonka** [comment]
> Thanks! You can probably make the destruction almost instantaneous by using an arena allocator for the strings: https://developers.google.com/protocol-buffers/docs/reference/arenas

Thank you, will check!
Meanwhile, here is the shortest test program for the original problem:

#include <windows.h>
#include "../Common/parallel_hashmap/phmap.h"
#include <cstring>
#include <vector>
#include <ppl.h>

typedef std::string SimpleString;

class srwlock {
	SRWLOCK _lock;
public:
	srwlock() { InitializeSRWLock(&_lock); }
	void lock() { AcquireSRWLockExclusive(&_lock); }
	void unlock() { ReleaseSRWLockExclusive(&_lock); }
};

typedef phmap::parallel_flat_hash_map<SimpleString, int, phmap::priv::hash_default_hash<SimpleString>,
	phmap::priv::hash_default_eq<SimpleString>,
	std::allocator<std::pair<const SimpleString, int>>, 8, srwlock> StrIntParallelMap;

class Dict
{
	StrIntParallelMap			m_stringsMap;
public:
    int addParallel(const SimpleString& str, volatile long* curIdx)
    {
        int newIndex = -1;
        auto inserted = m_stringsMap.insert(std::make_pair(str, newIndex));
        if (inserted.second) // we are the first to insert
        {
            newIndex = InterlockedIncrement(curIdx);
            m_stringsMap[str] = newIndex;
        }
        else // we are NOT first - someone already inserted the pair
        {
            while (newIndex < 0)
            {
                ::SwitchToThread();
                newIndex = m_stringsMap[str]; // 
            }
        }

        return newIndex;
    }

};


int main()
{
    size_t totalSize = 6000000;
    std::vector<int> values(totalSize);
    Dict dict;
    volatile long index = 0;
    concurrency::parallel_for(size_t(0), size_t(totalSize), [&](size_t i) {
        SimpleString s = "ab_uu_" +std::to_string(i % 1000000);
        values[i] = dict.addParallel(s, &index);
    });

    return 0;
}

Depends on the number of runs, it can get stuck on a first run, or it could have like 30 runs with no problems. 
I found out if I set switch /std::c++latest, it gets stuck more often.
