### ISSUE TITLE
SSSE3 checks

### ISSUE THREAD

**Issue by hellrot** [greg7mdp/parallel-hashmap#12]
There are two places protected with a check of PHMAP_HAVE_SSSE3, both in phmap.h. The protected intrinsics, _mm_movemask_epi8 and _mm_or_si128, are both SSE2 intrinsics.

It seems you could just remove those checks, the corresponding the #else case code, and simplify phmap_config.h to only test for (and require) SSE2.

**Comment by greg7mdp** [comment]
Thanks for the suggestion, but these two places also require _mm_sign_epi8 and _mm_shuffle_epi8 which are SSE3 if I'm not mistaken.

**Comment by hellrot** [comment]
Oops. You are correct, I overlooked those.
