### ISSUE TITLE
Cereal support

### ISSUE THREAD

**Issue by h-2** [greg7mdp/parallel-hashmap#120]
I read that phmap has "support for Cereal" and certain commits also indicate this. What this seems to mean is that cereal's default implementations for associative containers work for phmap. These implementations are, however, super slow, because they deserialise the data structure element-by-element.

You seem to have dump/load functions that read/write contiguous memory en-bloc (when not using Cereal). Could you provide overloads for cereal that make use of the same functionality? That would be really helpful!!

Happy holiday season and thank you for your work on this.

**Comment by greg7mdp** [comment]
Thanks for the suggestion, @h-2 , I think it is an excellent idea and it looks like cereal will support [it](https://uscilab.github.io/cereal/archive_specialization.html#:~:text=namespace%20cereal%20%7B%20%2F%2F%20Overload%20the%20std%3A%3Acomplex%20serialization,%28an%20input%20archive%29%20and%20saving%20%28an%20output%20archive%29.). I'll try to look into it this weekend.

**Comment by greg7mdp** [comment]
Hey @h-2 , I updated the code so that flat hash maps dump and load as one block when using a `cereal::BinaryOutputArchive`.
Please let me know how that works out for you, and happy holiday!

**Comment by h-2** [comment]
Thanks a lot and happy new year!

**Comment by h-2** [comment]
I forgot to give you an update on the performance: time for loading a dumped hash-map when from one hour to one minute :)

**Comment by greg7mdp** [comment]
> I forgot to give you an update on the performance: time for loading a dumped hash-map when from one hour to one minute :)

Awesome! Now that is a worthwhile speedup :-). Thanks for letting me know @h-2 !
