### ISSUE TITLE
Does phmap::btree_map support multi thread insert?

### ISSUE THREAD

**Issue by majestichou** [greg7mdp/parallel-hashmap#121]
My code is as follows:

int main()
{
    phmap::btree_map<int, int> map_final;
#pragma omp parallel for num_threads(3)
    for (int i = 0; i < 10; i++)
    {
        map_final.insert(std::make_pair(i, i));
    }

    for (auto iter = map_final.begin(); iter != map_final.end(); iter++)
    {
        printf("the value is %d\n", iter->second);
    }
    
   return 0;

}

The code can't run.

Dose  the following four types of data structure :
phmap::btree_set, phmap::btree_map, phmap::btree_multiset, phmap::btree_multimap
support multi thread insert?

**Comment by greg7mdp** [comment]
Hi @majestichou , `phmap::btree_*`  do **not** support multi thread insert as stated in the [README](https://github.com/greg7mdp/parallel-hashmap#thread-safety). You'll have to use a mutex to serialize inserts.

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟
