### ISSUE TITLE
Threadsafe combined erase and insert

### ISSUE THREAD

**Issue by karentierney** [greg7mdp/parallel-hashmap#122]
I would like to use a parallel_hash_set to keep only the set of keys that have not been inserted once already. Upon a second insert, if the key already exists in the set, it should be erased. Keys will ONLY ever be inserted either once or twice. In other words, every time I go to insert a key, something like,

```
if (!set.erase(key))
        set.insert(key);

```

This would work fine without threads, but I would like to do this on the order of a billion keys and the erase and insert are happening concurrently on many threads. Is there an efficient way to do this with the existing parallel_hash_set and it's own blocks and own mutex?

**Comment by greg7mdp** [comment]
I just added a new API to do what you need, `emplace_single`. So you would do:

```
Set set;
set.emplace_single(key, [&](const Set::constructor& ctor) { ctor(key); });
```

And it will do the `insert if not present else erase` under the internal mutex protection. I hope this works for you.

**Comment by karentierney** [comment]
Wow thank you! I will try it. I am not sure, however, about the meaning of the constructor? For me the type of my key is a sorted std::array<uint32_t, 3>.
I can also explain the context, since you may be interested.
Given a connected mesh of 3D tetrahedra, where a tetradron is defined by 4 integer indices, we wish to compute the boundary. The boundary is the set of triangles (faces of tetrahedra defined by 3 integer indices), where the triangle is not shared with any other triangles. The key of the set, for me, are std::array<uint32_t, 3>, one for each triangle or tetrahedron face, containing the vertex indices of the triangle face sorted in lexicographical order. I have another algorithm for this boundary computation that did not use hash set, but it had to store _all_ the faces at once, _boundary_ and _interior_ (repeated neighbor faces), and remove the _interior_ (repeats) at the end of the algorithm. One issue with my previous algorithm is it used too much memory. For example, 2 billion tetrahedra would require 96GB to store all the faces at once. The hash set memory footprint, instead I hope, will grow and shrink as faces are inserted and erased, but remain much smaller. At the end, the _boundary_ faces should be a magnitude order less than _all_ the faces (including _interior_ faces). If you have any other comments or suggestions related to memory usage of the hash set that may be very helpful.

**Comment by greg7mdp** [comment]
Hi @karentierney, incredibly enough I coded the exact same algorithm (not using phmap) a few years ago and indeed it works great. We called it the wetted face computation, i.e the faces that would get wet if you put the solid object in water. 

If you just pick the tetrahedrons at random and insert their (normalized) faces into the hash set, you may still use a good amount of peak memory, maybe around 40GB. However there is a way to minimize the peak memory used. You can spatialize your tetras in 3d space using an [octtree](https://en.wikipedia.org/wiki/Octree). Given the original bounding box of your solid:
1. subdivide the bounding box of the solid along each axis, creating 8 smaller boxes.
2. classify all your tetras into box 0 to 7, using the coordinate of the first node of the tetra
3. then, insert the faces of all the tetras of box 0 into the hash set, then those of box 1, ...

This will guarantee that all the inside faces of tetras of box 0 are eliminated before you start on box 1, and so on.

In my implementation, I even spatialized recursively (as long as one box had more than N tetras), but it may not be necessary for your use case.

Also, note that sorting the node of the faces may invert their winding order (flipping the face normal). In my case I was keeping track as to whether the winding of the faces was flipped, and then flipped it back after eliminating the inside (duplicated) faces.

**Comment by greg7mdp** [comment]
> I am not sure, however, about the meaning of the constructor?

The constructor is passed to the lambda you provide, just pass it whatever you need to build a face. For example:

```
using  Face = std::array<uint32_t, 3>;
using Set   =  phmap::parallel_flat_hash_set<Face, std::hash<Face>, std::equal_to<Face>, 
                                             std::allocator<Face>, 5, std::mutex>;

Set set;
for (auto& face : faces)
    set.emplace_single(face, [&](const Set::constructor& ctor) { ctor(face); });
```

**Comment by karentierney** [comment]
The new `emplace_single()` function is working for me. Thank you!
The spatial ordering of the tetra is a good idea like you suggest, but in my use case I do not have all the tetra in memory and so it would require an extra pass at the beginning to reorder them. I may consider that after I do some testing and timings on huge meshes.
Previously I have tried using a Morton ordering of vertices (Z-order) to speed up mesh operations by getting better thread cache coherency behavior. The cost of performing the ordering, however, outweighed any speedup I gained.

**Comment by greg7mdp** [comment]
Glad to hear the new API is working for you, thanks for lketting me know!

> I do not have all the tetra in memory

Just curious, how are they stored and how do you access them?

**Comment by karentierney** [comment]
The tetra (4 uint32_t indices per tetra) are stored in a file. The indices are often in no particular order. The number of tetra is known a priori. The minimum and maximum indices used by the tetra are unknown, but are bounded by a range we know a priori [0,N), i.e., the minimum and maximum index used by the tetra may or may not be 0 and N-1, respectively.

The file is read from an SSD. Basically for 8 logical cores, I have 8 worker threads running tasks, one kind of task reads a buffer of tetra indices, a second kind of task inserts the faces from a buffer into the hash set. For now, I am running with 8 buffers/ 

My memory issue seems to be solved by using parallel_flat_hash_set. That is great. Now I would really like to make it faster if possible. Interestingly, I increased the power of number of subsets all the way up to 12 (4096 tables), and it was still getting a little faster at the end. For example, going from power 11 to 12 still lowered the runtime by a few percent. From what I can see, the runtime is almost completely dominated by pthread_mutex_lock/unlock.

I am thinking how to reduce the amount of mutex lock/unlock. I wonder if there could be a way to insert a huge range of keys into the set with a single call. Internally, the hash set would sort the range of keys by hash value, then perform the mutex lock/unlock for a larger swath of elements only once. Alternatively, the function would take the range of elements and their hash value as input, and the elements would be pre-sorted by hash value on input.

**Comment by greg7mdp** [comment]
Hum, I don't think the alternatives you suggest would help. But do you know you could insert into the phmap without any locks.
There is an example for doing that in the bench.cc file in the repo. The relevant code is:

````
            size_t modulo = hash.subcnt() / num_threads;  
            for (const auto key : faces)
            {
                size_t hashval = hash.hash(key);                   // compute its hash
                size_t idx  = hash.subidx(hashval);             // compute the submap index for this hash
                if (idx / modulo == thread_idx)                 // if the submap is suitable for this thread
                      // insert this key
            }
```

So the file reading task would send the tetra buffer to all the hash inserting tasks, and each task would insert only within specific submaps which are accessed only by this thread => so no conflicts.

**Comment by karentierney** [comment]
Excellent. Now I get it! This should be a major speedup. I am just about to try this, but I have a small optimization question. Since in order to find whether a thread/worker/task should insert a key, I already needed to compute:

1. hash value for face (the key)
2. index of subset (corresponding to hash value)

Is there a way to insert the key into the correct subset _directly_ giving it the already computed hash value? For example, something analogous to:

```
size_t hashval = set.hash(face);
size_t idx  = set.subidx(hashval);
if (idx / modulo == thread_idx) {
    auto& subset   = set.sets_[idx].set_; // get the internal subset
    subset.emplace_single_with_hash(face, hashval, [&](const Set::constructor& ctor) { ctor(face); }); 
}
```
Here I would need the handle to the internal subset (some possibly? private class data).

**Comment by greg7mdp** [comment]
Yes, indeed I'll need to implement this extra API for you (I had already realized it). I'll try doing it over the weekend, but you can try with the current API if you want, you'll probably get most of the speedup anyways.

**Comment by greg7mdp** [comment]
Hi @karentierney, the API you need is already present:

```
    template <class K = key_type, class F>
    void emplace_single_with_hash(const key_arg<K>& key, size_t &hashval, F&& f);
```

**Comment by karentierney** [comment]
Well, not exactly. The method `emplace_single_with_hash()` is inaccessible in the public interface. `emplace_single_with_hash()` is a member of only the Inner subset. Also the inner subset, for example `set.set_[idx].set_` is inaccessible because `set_` a _protected_ member of `priv::parallel_hash_set`. Unless, is there a way to get a reference to the inner subset in the public interface?

**Comment by greg7mdp** [comment]
Oops, sorry, just added it (along with other changes which should not impact you).

**Comment by karentierney** [comment]
Thank you. BTW, what do you think would be the best way to write a hash to use with `parallel_flat_hash_set` for 3 uint32_t vertex indices? Currently I am using

```
struct hash3 {
    std::size_t operator()(const std::array<uint32_t, 3>& a) const {
        return phmap::HashState().combine(0, a[0], a[1], a[2]);
    }
};
```

**Comment by greg7mdp** [comment]
Your hash function seems perfect to me!
So was it faster without the locks?

**Comment by karentierney** [comment]
Surprisingly, using locks with 2^12 sub-tables was still slightly faster than my new no locks version. I played around with buffer sizes (how big of a chunk I process before I read another) but it had little effect on the no locks version. I also tried more sub-tables than workers, or the same number of sub-tables as the number of workers, but still no significant speedup.

When I get a chance, I will look into this and think about what else I could tweak with the tasks in the no lock version. It would be really great if I can make it faster. I have not yet counted how many faces are going into each sub-table (since we would like about the same number to go into each), which is partly why I asked if that is the best hash.

**Comment by greg7mdp** [comment]
I don't know how much work you are willing to do to speed this up, but I can suggest something if it is worthwhile to you.

Suppose your target machine supports 8 cores. You could have:

* one thread that just reads the tetras, generates the faces and sorts them into blocks to be processed by worker threads based on hash.subidx, and when a block is full, enqueue it in a lock_free queue.
* 8 worker threads which read from the lock-free queues and insert them into the parallel_flat_hash_set.

That way you don't have each thread processing all the tetras, and you split the sorting part and the inside face elimination part. I have the feeling this may be the fastest algo.

**Comment by karentierney** [comment]
Nice. We are thinking similarly, and I had started working on the following. I have the one task receive a buffer of tetra and fill an array with  

```
struct HashedFace {
    size_t _hash;
    std::array<uint32_t, 3> _vertex;
};

```
elements, where the 3 vertices are sorted. And at the end of this task, we sort this array and a second array of the corresponding hash.subidx together at the same time. Now we have contiguous ranges of faces for each subidx. I pass one subidx [start, end) to each worker to insert into hash set.

**Comment by karentierney** [comment]
Should this 2nd argument in the public interface be a const reference, it won't change the hashval right?

```
parallel_hashmap/phmap.h:3098:10: note: candidate function template not viable: 2nd argument ('const size_t' (aka 'const unsigned long')) would lose const qualifier
    void emplace_single_with_hash(const key_arg<K>& key, size_t &hashval, F&& f) {
```

**Comment by greg7mdp** [comment]
You are right, as references they should be const, but they don't need to be references at all. Fixed it.

**Comment by greg7mdp** [comment]
> we sort this array and a second array of the corresponding hash.subidx together at the same time. 

hum, sorting is a bit overkill, but it might be fine. Curious to see how this performs.

**Comment by karentierney** [comment]
By sorting the faces during preprocessing each array of faces (buffer or chunk) `std::array<uint32_t,3>`, I mean something analogous to what is called a "counting sort". Suppose we have a hash table with N sub-tables,   

1. for each face, re-order 3 vertex indices in increasing order
2. compute hash and corresponding sub-table for each face
3. count how many faces would end up in each sub-table. 
4. turn the count into a starting position of the faces for that sub-table, if the faces were to be reordered by sub-table.
5. compute a permutation of the face array:

```
        for (uint32_t i_face = 0; i_face < num_faces; ++i_face) {
            index[start[sub_table[i_face]]++] = i_face;
        }
```

 - sub_table is the sub table destination for each face (based on hash)
 - start is the starting position in the reordered array of faces for a sub-table (incremented every time we add a face)
 - index is the permutation of the face array

6. Reorder the faces array by the permutation in place using swaps. 
7. Decrement entries in the start array back to correspond to the first position where the faces of each sub-table begin.

Then I make N "insert" tasks to insert this chunk into the hash table and hand off to a thread pool. The tasks go into a work stealing queue scheduler. Each task uses the start array to only insert the faces for one sub-table.

With some tuning of 
 - face buffer size 
 - number of face buffers 
 - number of sub-tables

this preprocessing version beats the version where I was having each task iterate over ALL the faces in the face buffer, compute hash and sub-table destination, and insert. For larger numbers of tetra, 100 million in my testing, this preprocessing ends up 2X faster. And the preprocessing is maybe 1.5X faster than the version where tasks just throw all faces into the hash table with mutex locks (with a hash table of 2^12 sub-tables). In this preprocessing version I found 2^8 or 2^9 sub-tables are optimal. Therefore, I use 2^8 and I can store the sub-table index in a uint8_t.

So, this does solve my memory problem for super large sets of tetra. The speed is slower, however, than a version that only uses arrays (no hashtable) where all the faces (including repeated pairs for neighboring tetra in the interior) fit in memory. The no hashtable version is roughly 2X faster than this hashtable with preprocessing.

If I could figure out how to make my array-only version more streaming/progressive without having the complete mesh in memory, honestly, I would probably drop this hashtable version. Nevertheless, I will continue to use the parallel-hashmap repo for a handful of different uses. I already use it in other contexts. I initially was attracted to parallel-hashmap because I don't have to use ALL the abseil library when all I want is the hashtable! I have also used the binary tree.

We can close this issue. I was never sure this is the appropriate forum for all this detail. But you were a big help!

**Comment by greg7mdp** [comment]
Yeah, glad it worked out for you @karentierney , and thanks for the thorough explanation!
