### ISSUE TITLE
Compatibility with std::pmr::polymorphic_allocator?

### ISSUE THREAD

**Issue by lukekasz** [greg7mdp/parallel-hashmap#128]
I'm trying to use `phmap::parallel_flat_hash_map` with [std::pmr::polymorphic_allocator](https://en.cppreference.com/w/cpp/memory/polymorphic_allocator) and I get compile errors in both clang and MSVC due to the constructor taking an allocator calling `swap`. There are no issues calling the default constructor of `polymorphic_allocator`

Notes from the `polymorphic_allocator` docs linked above:

> **Notes**
> polymorphic_allocator does not propagate on container copy assignment, move assignment, or swap. As a result, move assignment of a polymorphic_allocator-using container can throw, and swapping two polymorphic_allocator-using containers whose allocators do not compare equal results in undefined behavior. 

`polymorphic_allocator` works fine with std maps and sets.

Here is the relevant part of the clang compile error.

> In file included from Main.cpp:15:
parallel_hashmap/phmap.h:134:21: error: no matching function for call to 'swap'
    return noexcept(swap(std::declval<T&>(), std::declval<T&>()));
                    ^~~~
parallel_hashmap/phmap.h:1541:10: note: in instantiation of function template specialization 'phmap::priv::IsNoThrowSwappable<std::experimental::pmr::polymorphic_allocator<std::pair<const unsigned int, unsigned int>>>' requested here
         IsNoThrowSwappable<allocator_type>())) {
         ^
parallel_hashmap/phmap.h:2029:9: note: in instantiation of exception specification for 'swap' requested here
        swap(tmp);
        ^
parallel_hashmap/phmap.h:1153:16: note: in instantiation of member function 'phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<unsigned int, unsigned int>, std::hash<unsigned int>, std::equal_to<unsigned int>, std::experimental::pmr::polymorphic_allocator<std::pair<const unsigned int, unsigned int>>>::move_assign' requested here
        return move_assign(
               ^
parallel_hashmap/phmap.h:2583:24: note: in instantiation of member function 'phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<unsigned int, unsigned int>, std::hash<unsigned int>, std::equal_to<unsigned int>, std::experimental::pmr::polymorphic_allocator<std::pair<const unsigned int, unsigned int>>>::operator=' requested here
            inner.set_ = EmbeddedSet(bucket_cnt / N, hash_param, eq, alloc);
                       ^
parallel_hashmap/phmap.h:2595:11: note: in instantiation of member function 'phmap::priv::parallel_hash_set<4, raw_hash_set, phmap::NullMutex, phmap::priv::FlatHashMapPolicy<unsigned int, unsigned int>, std::hash<unsigned int>, std::equal_to<unsigned int>, std::experimental::pmr::polymorphic_allocator<std::pair<const unsigned int, unsigned int>>>::parallel_hash_set' requested here
        : parallel_hash_set(0, hasher(), key_equal(), alloc) {}
          ^
Main.cpp:32:11: note: in instantiation of member function 'phmap::priv::parallel_hash_set<4, raw_hash_set, phmap::NullMutex, phmap::priv::FlatHashMapPolicy<unsigned int, unsigned int>, std::hash<unsigned int>, std::equal_to<unsigned int>, std::experimental::pmr::polymorphic_allocator<std::pair<const unsigned int, unsigned int>>>::parallel_hash_set' requested here
        : hashMap(memoryResource)

Code sample that fails to compile.

```
#if __has_include(<experimental/memory_resource>)
#include <experimental/memory_resource>
namespace std
{
    namespace pmr = experimental::pmr;
}
#elif __has_include(<memory_resource>)
#include <memory_resource>
#elif
#error <memory_resource> is missing 
#endif

#include <parallel_hashmap/phmap.h>

struct MyStruct
{
    template<typename Key, typename Value>
    using ParallelFlatHashMap = phmap::parallel_flat_hash_map<Key, Value, std::hash<Key>, std::equal_to<Key>, 
                            std::pmr::polymorphic_allocator<std::pair<const Key, Value>>>;

    ParallelFlatHashMap<uint32_t, uint32_t> hashMap;

    // No compile errors
    MyStruct() 
    {
    }

    // Compile errors
    MyStruct(std::pmr::memory_resource* memoryResource = std::pmr::get_default_resource()) 
        : hashMap(memoryResource)
    {
    }
};
```

**Comment by greg7mdp** [comment]
Hi @lukekasz , please try changing the `#if 1` [there](https://github.com/greg7mdp/parallel-hashmap/blob/dab73d4b0e3d09822076a4e5b20b29a7d4b5aaff/parallel_hashmap/phmap.h#L2650) to `#if 0`, and let me know if it fixes your issue. Hopefully you use a gcc version >= 7.1.

**Comment by greg7mdp** [comment]
@lukekasz you can also try the latest version of phmap. You'll need gcc >= 7.1 and -std=c++17 or higher.

**Comment by lukekasz** [comment]
Thanks for the speedy response.

I checked the latest fix you made at https://github.com/greg7mdp/parallel-hashmap/commit/79702346265d35d8e10033c49d5af0a8e581f936

It built correctly on clang for me. 

It didn't build in MSVC because `__cplusplus` is not set correctly unless you pass another [/Zc:__cplusplus (Enable updated __cplusplus macro)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) flag to the compiler.

I did a little bit of research and found that `_MSVC_LANG` can be used instead and this [Which values can _MSVC_LANG have?](https://stackoverflow.com/questions/43639122/which-values-can-msvc-lang-have) question says that you can check for C++17 using `_MSVC_LANG > 201402`. So I changed the `#if` in your latest changes to

```
#if (__cplusplus >= 201703L || _MSVC_LANG >= 201402) && (defined(_MSC_VER) || defined(__clang__) || (defined(__GNUC__) && __GNUC__ > 6))
```
And now it also builds correctly in MSVC 2022 for me.

**Comment by greg7mdp** [comment]
Great, thanks for investigating this @lukekasz, I just added your change.
