### ISSUE TITLE
Multiple threads using the same hash table

### ISSUE THREAD

**Issue by PietropaoloFrisoni** [greg7mdp/parallel-hashmap#131]
Good morning,
I have a pretty simple question.

How can you make sure that more threads (therefore on the same machine) can use the same hash table loaded in memory?

I have a situation like this:

```
struct MyKey
{
  friend size_t hash_value(const MyKey &k)
  {
    return phmap::HashState().combine(0, k.key[0], k.key[1], k.key[2], k.key[3], k.key[4], k.key[5], k.key[6], k.key[7], k.key[8]);
  }

  bool operator==(const MyKey o) const { return key == o.key; }

  uint8_t &operator[](int idx) { return key[idx]; }

  std::array<uint8_t, 9> key;
};
```

I am using a Class: 

```
class MyClass
{

(...)

public:

  using Hash = phmap::flat_hash_map<MyKey, double>;
  Hash h{};

};
```
Here below I would like to load into memory a hash table (just once) and then initialize the hash table in each class object
constructor (each one belonging to a different thread) with the hash table loaded into memory:

```
   (...)
    std::string hashed_tables_path_assigned = "generic/path/to/stored/hash/table";

    omp_set_num_threads(number_of_threads);

    using Hash = phmap::flat_hash_map<MyKey, double>;
    Hash h{};
    phmap::BinaryInputArchive ar_in(&hashed_tables_path_assigned[0]);
    h.phmap_load(ar_in);

#pragma omp parallel for
    for (int thread_id = 0; thread_id < number_of_threads; thread_id++)
    {
        MyClass Classobject (... )   // here I would like to initialize each object so that it can use the same hash table
    }

```

Please tell me if I explained myself properly or if something is unclear.

It should be a simple syntax problem. The only way I was able to get this to work was to have each thread load a copy of the hash table into memory, which is obviously a terrible solution.

A thousand thanks!

**Comment by greg7mdp** [comment]
Hi @PietropaoloFrisoni ,

First you should use a parallel hash map, like `using Hash = phmap::parallel_flat_hash_map<MyKey, double
                                          phmap::priv::hash_default_hash<MyKey>,
                                          class Eq    = phmap::priv::hash_default_eq<MyKey>,
                                          class Alloc = phmap::priv::Allocator<
                                                               phmap::priv::Pair<const MyKey, double>>,
                                          4, 
                                          std::mutex>;`.

Then change your class to hold a shared_ptr insteead of a hash map:

```
#include <memory>

class MyClass
{

(...)

public:
  using Hash = phmap::parallel_flat_hash_map<MyKey, double
                                          phmap::priv::hash_default_hash<MyKey>,
                                          class Eq    = phmap::priv::hash_default_eq<MyKey>,
                                          class Alloc = phmap::priv::Allocator<
                                                               phmap::priv::Pair<const MyKey, double>>,
                                          4, 
                                          std::mutex>;

  // constructor accepting a shared_ptr
  MyClass(std::shared_ptr<Hash> &hash) : h(hash) {}

  std::shared_ptr<Hash> h;

};
```

and do that:

```
#pragma omp parallel for
    auto hash = std::make_shared<MyClass::Hash>();
    hash->reserve(10000); // or whatever size is appropriate
    ...
    for (int thread_id = 0; thread_id < number_of_threads; thread_id++)
    {
        MyClass Classobject (hash);   // here I would like to initialize each object so that it can use the same hash table
    }
```

**Comment by PietropaoloFrisoni** [comment]
I forgot to mention that the table is *only read* by multiple threads, the threads don't actually write on it (the table has been filled and dumped to disk before).

Am I forced to use a parallel hash map anyway?

**Comment by greg7mdp** [comment]
Of no, in that case you don't need a parallel one, the one you had was fine.

**Comment by PietropaoloFrisoni** [comment]
Great.

Therefore, what's the explicit correct syntax keeping the same flat map?

**Comment by greg7mdp** [comment]
Just update the `using` directive to what you had and you are good to go.

**Comment by greg7mdp** [comment]
Are you having trouble doing this?

**Comment by greg7mdp** [comment]
the new code I sent still will work even with the old hash map type

**Comment by PietropaoloFrisoni** [comment]
Sorry but I don't understand what you wrote (I never used shared pointers in C++).

I paste here my code again:

```
struct MyKey
{
  friend size_t hash_value(const MyKey &k)
  {
    return phmap::HashState().combine(0, k.key[0], k.key[1], k.key[2], k.key[3], k.key[4], k.key[5], k.key[6], k.key[7], k.key[8]);
  }

  bool operator==(const MyKey o) const { return key == o.key; }

  uint8_t &operator[](int idx) { return key[idx]; }

  std::array<uint8_t, 9> key;
};
```

```
class MyClass
{

(...)

public:

  using Hash = phmap::flat_hash_map<MyKey, double>;
  Hash h{};

};
```

```
   (...)
    std::string hashed_tables_path_assigned = "generic/path/to/stored/hash/table";

    omp_set_num_threads(number_of_threads);

    using Hash = phmap::flat_hash_map<MyKey, double>;
    Hash h{};
    phmap::BinaryInputArchive ar_in(&hashed_tables_path_assigned[0]);
    h.phmap_load(ar_in);

#pragma omp parallel for
    for (int thread_id = 0; thread_id < number_of_threads; thread_id++)
    {
        MyClass Classobject (... )   // here I would like to initialize each object so that it can use the same hash table
    }
```
Notice that the hash table has to be loaded from disk into the memory before the parallel region (otherwise each thread loads a different copy) and me and my co-workers simply have to find a way to *read (only)* the hash table from different threads independently. 

Inside the MyClass class, the hash tables is currently used as:
```
(...)
MyKey kNW{ti_1, ti_2, ti_3, ti_4, tb1,
                        tb2, tb3, 0, 0};
(...)
kNW[7] = kNE[7] = t5;
(...)
kNW[8] = kNE[8] = t7;
(...)
variable = h[kNW];
```

We tried to modify in such a way that it is similar to your example but we got a lot of errors (for example a ">" missing somewhere), which unfortunately we cannot fix as we don't know C++ enough to understand what we are actually doing.

**Comment by PietropaoloFrisoni** [comment]
Maybe the only question is: if h is a shared pointer to the hash table, what is the syntax to use the hash table by working with h instead of 
```
h[MyKey` {ti_1, ti_2, ti_3, ti_4, tb1,
                        tb2, tb3, 0, 0}] 
```
?

**Comment by greg7mdp** [comment]
use `(*h)[MyKey{...}]`

**Comment by greg7mdp** [comment]
let me know if you need help, we can do an online meeting.

**Comment by PietropaoloFrisoni** [comment]
I thought about using a simple pointer, but when I try to load a map a get a segmentation fault, which I don't know how to fix.

If you have time that would be great! Can I write you in private (where can I find your email)?

**Comment by greg7mdp** [comment]
it is my github id @ gmail.com
