### ISSUE TITLE
Compilation on windows with VS 2029 and invoke

### ISSUE THREAD

**Issue by Nosenzor** [greg7mdp/parallel-hashmap#132]
Use __cpp_lib_result_of_sfinae to control invoke. in phmap_base.h (FIX compilation error on VS 2019)
#ifdef **__cpp_lib_result_of_sfinae**
using invoke_result_t = typename std::invoke_result_t<F, ArgTypes...>;
#else
using invoke_result_t = typename std::result_of<F(ArgTypes...)>::type;
#endif
instead of  
#if __cplusplus >= 201703L
using invoke_result_t = typename std::invoke_result_t<F, ArgTypes...>;
#else
using invoke_result_t = typename std::result_of<F(ArgTypes...)>::type;
#endif

BTW Thanks a lot for your amazing work !!!

**Comment by greg7mdp** [comment]
VS 2029? You must be a time traveler! :-)
cool, thanks, is this change compatible with gcc and clang as well?

**Comment by greg7mdp** [comment]
Thanks a lot for the suggestion btw... and the kind words!
Trying your suggestion right now.

**Comment by greg7mdp** [comment]
doesn't work on linux when building with `-std=c++11`:

```
In file included from /home/runner/work/parallel-hashmap/parallel-hashmap/parallel_hashmap/phmap.h:69,
                 from /home/runner/work/parallel-hashmap/parallel-hashmap/tests/compressed_tuple_test.cc:15:
/home/runner/work/parallel-hashmap/parallel-hashmap/parallel_hashmap/phmap_base.h:333:43: error: ‘invoke_result_t’ in namespace ‘std’ does not name a template type
  333 |     using invoke_result_t = typename std::invoke_result_t<F, ArgTypes...>;
      |                   
```

**Comment by greg7mdp** [comment]
@Nosenzor what was your issue exactly. I build the old version without problem using vs 2019.

**Comment by greg7mdp** [comment]
@Nosenzor , does the current version fix your issue?

**Comment by greg7mdp** [comment]
Oh yes, that's probably the issue, I'll update the vcpkg.

**Comment by Nosenzor** [comment]
Yeah. when I copy your headers in vcpkg cache and recompile it is smooth. I noticed the file from vcpkg were dated from may 2020 !

**Comment by greg7mdp** [comment]
Thanks! I have submitted a PR to update the vcpkg https://github.com/microsoft/vcpkg/pull/23363

**Comment by Nosenzor** [comment]
FYI : 
Building package parallel-hashmap[core]:x64-windows...
-- Downloading https://github.com/greg7mdp/parallel-hashmap/archive/1.34.tar.gz -> greg7mdp-parallel-hashmap-1.34.tar.gz...
-- Extracting source C:/dev/vcpkg/downloads/greg7mdp-parallel-hashmap-1.34.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/parallel-hashmap/src/1.34-2e96d01166.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows

And now build is OK
