### ISSUE TITLE
Dump/load as array for parallel hash map

### ISSUE THREAD

**Issue by ila** [greg7mdp/parallel-hashmap#133]
Hello, I would like to use the dump/load as array feature for a parallel flat hash map as well, serializing empty space as zeros. Is that possible and if so, what should I keep in mind when implementing it? 

Furthermore I noticed that if I reserve some space in a parallel hash map, this information gets lost when dumping and loading - the loaded map will always have a load factor around 1, making a rehash necessary when performing more insertions. Any way to fix this?

**Comment by greg7mdp** [comment]
Hi @ila , if you use the latest version of phmap, this should work as you wish, provided the Keys and Values in the hash_map are std::trivially_copyable.

**Comment by ila** [comment]
Oh you are right, thank you very much! Don't know how I missed this, I even went through the commit messages. Then I will send you a PR tomorrow with updated documentation :) many many thanks for maintaining this work, it's doing wonders for my master's thesis

**Comment by greg7mdp** [comment]
PS: vcpkg and conan will shortly be updated to the latest version.
