### ISSUE TITLE
Using With Clang on Windows

### ISSUE THREAD

**Issue by tonyb983** [greg7mdp/parallel-hashmap#135]
Hi, I'm terrible at C++ in general so there's a decent chance this error is mine (if that's the case I'll close / delete issue) but I am getting a compile error using this library, which was installed via `vcpkg`, with `Clang/LLVM` on `Windows`. Specifically, in `phmap_base.h` at line 3689 in this segment:

```cpp
#if defined(__GXX_RTTI)
    #define PHMAP_INTERNAL_HAS_CXA_DEMANGLE
#endif

#ifdef PHMAP_INTERNAL_HAS_CXA_DEMANGLE
    #include <cxxabi.h>
#endif
```

It appears that unless you specifically disable RTTI, clang sets the flag `__GXX_RTTI`, causing your library to try and include `cxxabi.h` which is not found on Windows. I changed the first quoted line above to `#if defined(__GXX_RTTI) && !defined(_WIN32)` and it works fine, but who knows what that may have broken elsewhere for different platforms.

Again, if there's something obvious I missed or anything stupid here (***other** than me using Clang on Windows with vcpkg*) please let me know.

**Comment by greg7mdp** [comment]
Hi @tonyb983 , Is this the clang that can be installed with Visual Studio? On my install I see the file is present in:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\include\usr\include\c++\5\cxxabi.h`

**Comment by tonyb983** [comment]
No, standalone (full) installation of Clang (v13.0.1) which apparently does not include that file (I just grepped through the install directory). I do have MSVC installed as well I just don't use it, maybe I can find it there and make it available to Clang...

**Comment by greg7mdp** [comment]
Actually I'm not quite sure why this include is needed. I'll try removing it.
