### ISSUE TITLE
Keep original bucket count when copying a map

### ISSUE THREAD

**Issue by ila** [greg7mdp/parallel-hashmap#136]
Hello,
I am facing the following issue: I want to assign a map to other, however I lose the bucket count while doing so. The following code explains it better:
```
auto map1 = phmap::parallel_flat_hash_map<int, int>(15000);
for (int j = 0; j < 1000; j++)
    map1.insert(std::make_pair(j, j));
phmap::parallel_flat_hash_map<int, int> map2;
map2 = map1;
std::cout << "map1 " << map1.size() << " " << map1.bucket_count() << "\n";
std::cout << "map2 " << map2.size() << " " << map2.bucket_count() << "\n";
```
The output of this is:
```
map1 1000 262128
map2 1000 1648
```

I would like map2 to have 26k buckets too. I know there are other ways to copy, but I am implementing code with templates and this is just the simpler way to assign. Any idea on how to fix this?

**Comment by greg7mdp** [comment]
Can you do:

```
phmap::parallel_flat_hash_map<int, int> map2(map1.begin(), map1.end(), map1.bucket_count());
```

**Comment by ila** [comment]
No, since I need a syntax like `Key = Key, Value = Map` (I am implementing a buffer with templates)

**Comment by greg7mdp** [comment]
Hum, I don't understand what your use case is? Can you be more specific? Maybe share some code?

**Comment by greg7mdp** [comment]
It would not be difficult to support this, but I'm not sure it is always desirable.

**Comment by ila** [comment]
This is the cache I am using: [https://github.com/facebook/hhvm/blob/master/hphp/util/concurrent-lru-cache.h](https://github.com/facebook/hhvm/blob/master/hphp/util/concurrent-lru-cache.h)
I want to create a cache in which I can insert parallel hash maps as values. As you can see, the insertion method above relies on making a copy of the object. 

I can probably refactor all of the previous code without templates, or try to implement this myself but I am wondering which one of the options is less time consuming :)

**Comment by greg7mdp** [comment]
Can you try this change in phmap.h:

![image](https://user-images.githubusercontent.com/1496907/161314816-7868641d-27ec-4b5a-8441-9c0d76ac66ef.png)

**Comment by greg7mdp** [comment]
Actually I'll make the change in phmap because it is specified in the spec.
![image](https://user-images.githubusercontent.com/1496907/161315540-4f6417a7-eeb3-456f-8f7e-2d1e0a2a364f.png)

**Comment by greg7mdp** [comment]
@ila thanks for reporting the issue, it should be fixed now, if not let me know.

**Comment by ila** [comment]
Thank you so much! However, he change you suggested outputs on the first snipped of code
```
map1 1000 262128
map2 1000 524272
```
Tried with other values too and I think that reserving the same number of buckets as the previous possibly overestimates

**Comment by greg7mdp** [comment]
Thanks again, please try latest

**Comment by ila** [comment]
Now it works, thank you very much :)

**Comment by greg7mdp** [comment]
@ila, I think this lru_cache may mot be as fast as expected in your use case because it copies the values always, instead of moving them when possible.
