### ISSUE TITLE
phmap_dump does not preserve the correct number of buckets

### ISSUE THREAD

**Issue by ila** [greg7mdp/parallel-hashmap#137]
It's me again, I almost feel bad for opening issues on Sunday morning :) following snippet of code:
```
phmap::BinaryOutputArchive ar_out("/tmp/ht");
phmap::BinaryInputArchive ar_in("/tmp/ht");

phmap::parallel_flat_hash_map<uint32_t, uint32_t> map1(15000);
phmap::parallel_flat_hash_map<uint32_t, uint32_t> map2;

for (int j = 0; j < 10; j++)
    map1.insert(std::make_pair(j, j));

std::cout << "map1 " << map1.size() << " " << map1.bucket_count() << "\n";
map1.phmap_dump(ar_out);

map2.phmap_load(ar_in);
std::cout << "map2 " << map2.size() << " " << map2.bucket_count() << "\n";
```
The output of this is:
```
map1 10 262128
map2 10 114681
```
If I change the maximum value of `j` in the loop, the output of the bucket count of map2 changes. i.e. the more I fill the map, the more likely is the correct load factor to be dumped - however, the load factor should be preserved even if I insert 1 value and then write it to disk. I believe it is a problem while dumping, not while loading, since the size of the files written on disk reflect the bucket count found by phmap_load. In other words, the map is written to disk with the wrong bucket count to begin with.

Edit: seems like the issue happens when some of the submaps are empty, i.e. if the size of the raw_hash_set is zero, then it does not get written to disk. In my previous example, the 10 values were distributed only in 7 maps, of which the capacity is 16 383. Only these 7 are written to disk, making the total bucket count 114 681. However, I am not too confident that this is an easy fix - it would imply being able to serialize empty sets and read them from disk, which does not really make sense in my opinion.

On the other hand, I would like my map not to be rehashed when I read it from disk and I proceed to do a lot of consecutive insertions, since rehashing is expensive - is there any way to allocate the bucket count of the other submaps when reading an empty submap?

**Comment by ila** [comment]
Update: I tried and fixed it myself, let me know what you think of the following code. For reference, this is `phmap_dump.h` starting from line 123:
```
    size_t bucket_count = 0;
    for (size_t i = 0; i < submap_count; ++i) {
        auto& inner = sets_[i];
        typename Lockable::UniqueLock m(const_cast<Inner&>(inner));
        if (!inner.set_.phmap_load(ar)) {
            std::cerr << "Failed to load submap " << i << std::endl;
            return false;
        }
        if (inner.set_.size_ != 0) {
            bucket_count = inner.set_.capacity_;
        }
    }

    for (size_t i = 0; i < submap_count; ++i) {
        auto &inner = sets_[i];
        if (inner.set_.size_ == 0) {
            inner.set_ = raw_hash_set<Policy, Hash, Eq, Alloc>(bucket_count);
        }
    }
```
The reason why I am using an additional `for` loop is simply that if I understand correctly it is not given that `map_i` will be filled before `map_i+1`, so before having a capacity we need to make sure at least one map is loaded and that could be the last one. If something like this would fit the designed functionality, I will proceed making a PR.

**Comment by greg7mdp** [comment]
Hi @Ila, than you for the report, this is a bug in phmap_dump/load. Your fix is not the right one, please try the new version I just pushed in.

**Comment by ila** [comment]
Thank you so much, this seems to be working :) just a clarification, do empty submaps get written on disk now serialized as zeros?

**Comment by greg7mdp** [comment]
If they are empty only the size and capacity are written on disk. But if they have even one element, then the whole array is written on disk, and it can be large if you set a large capacity at creation or with reserve().

**Comment by ila** [comment]
Awesome, this sounds like the behaviour I would expect :) again many thanks for the support and patience

**Comment by greg7mdp** [comment]
No problem, thank you!
