### ISSUE TITLE
What's mean "move the keys and values in memory" ?

### ISSUE THREAD

**Issue by mlkt** [greg7mdp/parallel-hashmap#14]
> The flat hash maps may move the keys and values in memory. So if you keep a pointer to something inside a flat hash map, this pointer may become invalid when the map is mutated. The node hash maps don't, and should be used instead if this is a problem.

What's mean "move the keys and values in memory" ? 
Why "pointer may become invalid"？I can't understand.

Because used memcpy() and didn't use the copy constructor?

**Comment by greg7mdp** [comment]
Hi @mlkt,

Suppose you have this class:
```
struct A {
    int x;
    int y;
};
```
and a map `phmap::flat_hash_map<int, A> map;`.

Now you insert values into the map:

```
map[1] = A{22,34};
map[2] = A{38,99};
map[3] = A{85,65};
```
What is dangerous is to store a pointer to a value inside the flat_hash_map, as in:
```
int *p = &map[2].x;
printf("%d\n", *p); // => prints 38
```

When new values are inserted into the phmap, the value pointed by p is likely to change:

```
map[4] = A{4,5};
map[5] = A{6,7};
printf("%d\n", *p); // => prints -572662307
```

Hope this helps!

**Comment by mlkt** [comment]
OK, thanks, I see. If so, in a multithreaded environment, after getting a value's reference, the reference maybe become invalid before read it ? (even if mutex are used)

**Comment by greg7mdp** [comment]
> in a multithreaded environment, after getting a value's reference, the reference may become invalid before read it ? (even if mutex are used)

yes, unfortunately.

**Comment by mlkt** [comment]
so in this case,  use parallel_node_hash_map ?

**Comment by greg7mdp** [comment]
parallel_node_hash_map should be OK for a value reference (unless it is deleted from another thread of course), but iterators would not work reliably.

**Comment by mlkt** [comment]
OK, Thanks!
