### ISSUE TITLE
A way to erase all elements matching a value/predicate

### ISSUE THREAD

**Issue by HolyBlackCat** [greg7mdp/parallel-hashmap#141]
There's a new addition to `std`: [`std::erase_if(container, predicate)` and `std::erase(container, value)`](https://en.cppreference.com/w/cpp/container/vector/erase2) that erase all elements from a container that match a condition.

It seems so far it's implemented only for the btree containers (as a simple `.erase()` loop).

I think it would be nice to have for the hash containers too.

**Comment by greg7mdp** [comment]
Yes, it would indeed be nice. Please give me a few days to look into this.

**Comment by greg7mdp** [comment]
@HolyBlackCat I added support for `std::erase_if` for hash containers. I don't believe `std::erase` is in the standard for associative containers. Please let me know if I missed something.
