### ISSUE TITLE
memory buffer support

### ISSUE THREAD

**Issue by wjiali6** [greg7mdp/parallel-hashmap#144]
I'm testing on parallel-hashmaps for sometime, in my usecase parallel-hashmaps is about 40% faster than std::unordered_map,[vs 2019 16.11.7 with Win10 i7-8565U CPU @ 1.80GHz].
My code runs on a fairly low memory (50Mbs at peak) ,but allocates small memory chunks very often and I discover  parallel-hashmaps waiting for malloc nearly half of the time. Is there any way let parallel-hashmaps uses memory buffer allocated in advance?

**Comment by greg7mdp** [comment]
What is the exact type of your parallel hashmap?

**Comment by wjiali6** [comment]
Thank you for your reply.
I'm using phmap::flat_hash_map with some custom structs like 
phmap::flat_hash_map<int,phmap::flat_hash_map<std::string,struct _{...}>>

**Comment by wjiali6** [comment]
copy insert I think, I use a pattern like  auto &field = record[field_key];   to find or insert new ( in my case this causes insertion most of the time)
The key strings' length varies from 3 to 20 bytes ,and field values are fixed-length struct.
I memcpy or use copy construct my field values accordingly:

memcpy(field.value,some_value,sizeof(char8_t) * 10);  
or 
field.value_string_view = some_value;   //according to the field type ,and as mentioned above value length is fixed length struct

**Comment by greg7mdp** [comment]
Hum, hard to really tell what the issue could be. If you think there is a problem, please submit a small example demonstrating it (full source code so I can build it).

**Comment by greg7mdp** [comment]
Closing this, please submit an issue with a sample program reproducing the issue, and which does not require Qt which I don't have installed.
