### ISSUE TITLE
Warning when compiling with the Intel C++ compiler

### ISSUE THREAD

**Issue by dgazzoni** [greg7mdp/parallel-hashmap#145]
I've added parallel-hashmap to one of my projects, which I compile with `-Wall -Wextra -Werror`. When trying to compile the project with the Intel C++ compiler (version 2021.6.0 20220226), I get the following warnings:

```
/home/.../parallel-hashmap/parallel_hashmap/phmap.h(424): warning #68: integer conversion resulted in a change of sign
          auto special = _mm_set1_epi8(static_cast<uint8_t>(kSentinel));
                                       ^

/home/.../parallel-hashmap/parallel_hashmap/phmap.h(432): warning #68: integer conversion resulted in a change of sign
          auto special = _mm_set1_epi8(static_cast<uint8_t>(kSentinel));
```

This is on the most recent commit (655dee9).

Due to the use of -Werror, it breaks my build. I've removed this flag for now but it would be great if this were fixed so I could bring the flag back. Thanks.

**Comment by greg7mdp** [comment]
Thanks for the report @dgazzoni . I can't right now, but I'll look into it in a few days.

**Comment by greg7mdp** [comment]
Why do you thing the commit you referenced causes the issue?

**Comment by greg7mdp** [comment]
@dgazzoni  Please try the fix I just checked in. I don't have an intel compiler to try.

**Comment by dgazzoni** [comment]
> Why do you thing the commit you referenced causes the issue?

I don't, actually. It's the only commit I tested, so all I can say is that the issue is present there, no idea when it was introduced.

> @dgazzoni Please try the fix I just checked in. I don't have an intel compiler to try.

Will do. I will get back to you soon.

**Comment by greg7mdp** [comment]
Closing this, please reopen if needed. Thank you @dgazzoni
