### ISSUE TITLE
Need help ,Assertion failed,constructed value does not match the lookup key

### ISSUE THREAD

**Issue by xiaoyifang** [greg7mdp/parallel-hashmap#146]
Assertion failed: PolicyTraits::apply(FindElement{*this}, *iterator_at(i)) == iterator_at(i) && "constructed value does not match the lookup key", file \parallel_hashmap/phmap.h, line 2216

I use parallel_flat_hash_map together with QtConcurrent::blockingMap ,a multi thread utils.

**Comment by greg7mdp** [comment]
Hi @xiaoyifang , can you provide a small program reproducing the  issue?

Thanks!

**Comment by xiaoyifang** [comment]
I use it with qt ,and I'll try to reproduce it with a smaller application

**Comment by xiaoyifang** [comment]
[qt-qstring-vasprinf (2).zip](https://github.com/greg7mdp/parallel-hashmap/files/8866198/qt-qstring-vasprinf.2.zip)

**Comment by greg7mdp** [comment]
You need to have a mutex type to protect accesses to the parallel_flat_hash_map. See this for example https://github.com/greg7mdp/parallel-hashmap/blob/master/examples/allmaps.cc#:~:text=using%20Map%20%3D%20phmap,std%3A%3Amutex%3E%3B

**Comment by xiaoyifang** [comment]
thanks ,I'll look into it,
but isn't the parallel_flat_hash_map use a built-in mutex.

**Comment by xiaoyifang** [comment]
I changed to this ,still error.
```
using Map = phmap::parallel_flat_hash_map<QString, QVector< uint32_t >,
                                          std::hash<QString>,
                                          std::equal_to<QString>,
                                          std::allocator<std::pair<const QString, QVector< uint32_t >>>,
                                          4,
                                          std::mutex>;
```

**Comment by greg7mdp** [comment]
OK, I can't right now, but I'll look into this in a week. Thanks!

**Comment by xiaoyifang** [comment]
That's ok.Thanks a lot

**Comment by greg7mdp** [comment]
@xiaoyifang - I'm sorry, I don't have Qt installed. I would need a small sample reproducing the issue and not using Qt.

**Comment by BiteTheDDDDt** [comment]
I meet same problem, under multi-threaded read and write, an error will occur.
```cpp
template <typename K, typename V>
    using ParallelMap =
            phmap::parallel_flat_hash_map<K, V, phmap::Hash<K>, phmap::EqualTo<K>,
                                          std::allocator<std::pair<const K, V>>, 4UL, std::mutex>;
ParallelMap<std::string_view, size_t> mp;



phmap.h:2221: void phmap::priv::raw_hash_set<Policy, Hash, Eq, Alloc>::emplace_at(size_t, Args&& ...) [with Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string_view<char, std::char_traits<char> >&&>, std::tuple<long unsigned int&>}; Policy = phmap::priv::FlatHashMapPolicy<std::basic_string_view<char>, long unsigned int>; Hash = phmap::Hash<std::basic_string_view<char> >; Eq = phmap::EqualTo<std::basic_string_view<char> >; Alloc = std::allocator<std::pair<const std::basic_string_view<char>, long unsigned int> >; size_t = long unsigned int]: Assertion `PolicyTraits::apply(FindElement{*this}, *iterator_at(i)) == iterator_at(i) && "constructed value does not match the lookup key"' failed.
```

btw, if use std::string to replace string_view, everything is work fine.

**Comment by greg7mdp** [comment]
Hi, I would need an example to reproduce the issue. When using a std::string_view, it is possible that another thread could change the string that the string_view is looking at while it is being inserted. This would be a logic problem, not a phmap issue.
