### ISSUE TITLE
Additional locks are required?

### ISSUE THREAD

**Issue by ManciuCen** [greg7mdp/parallel-hashmap#151]
Dear developer:
I was interested in parallel-hashmap and ready to used in my application, from the READ.md file I saw the following message:

> If a single hash table is being written to by one thread, then all reads and writes to that hash table on the same or other threads must be protected. For example, given a hash table A, if thread 1 is writing to A, then thread 2 must be prevented from reading from or writing to A.

Also:

> The parallel tables can be made internally thread-safe for concurrent read and write access, by providing a synchronization type (for example [std::mutex](https://en.cppreference.com/w/cpp/thread/mutex)) as the last template argument. Because locking is performed at the submap level, a high level of concurrency can still be achieved. Read access can be done safely using if_contains(), which passes a reference value to the callback while holding the submap lock. Similarly, write access can be done safely using modify_if, try_emplace_l or lazy_emplace_l. However, please be aware that iterators or references returned by standard APIs are not protected by the mutex, so they cannot be used reliably on a hash map which can be changed by another thread.

So, I would like to know if I use insert function like 'try_emplace_l'(and use std::shared_mutex as the last template argument in table constructor) in thread 1 while the thread 2/3/4.. was trying to read or write to the same table, do I still need to add the additional lock like this:
thread 1:
```
std::shared_mutex s_mu;
{
    std::unique_lock<std::shared_mutex> lock(s_mu);
    mytable.try_emplace_l(xxx);
}
```
thread 2:
```
{
    std::unique_lock<std::shared_mutex> lock(s_mu);
    auto iter = mytable.if_contains();
}
```
or I can just use like this:

thread 1:
```
mytable.try_emplace_l(xxx);
```
thread 2:
```
// do something
auto iter = mytable.if_contains();
// maybe also try to write
mytable.try_emplace_l(xxx);
```
if the latter is right, are only 'if_contains()', 'modify_if()', 'try_emplace_l()', 'lazy_emplace_l()' these four APIs satisfied thread safe?

 A thousand thanks!! :)

**Comment by greg7mdp** [comment]
Yes, these APIs are already thread-safe (if you provided a mutex type as the last template parameter), and you do *not* need std::unique_lock. So your second version is fine.

Also the more internal submaps you use, the less likely it is that your threads will stop waiting for a mutex.

**Comment by ManciuCen** [comment]
Thanks for your reply! @greg7mdp 

> Yes, these APIs are already thread-safe (if you provided a mutex type as the last template parameter), and you do _not_ need std::unique_lock. So your second version is fine.

What about the erase() APIs? Are there any thread-safe remove-like function?

> Also the more internal submaps you use, the less likely it is that your threads will stop waiting for a mutex.

May I ask which parameter I can set to specify the nums of internal submaps?

**Comment by greg7mdp** [comment]
The API `erase(const key_arg<K>& key)` is thread_safe, Don't use the one with iterators.

The first remplate parameter N creates 2^N submaps. When N==4 it creates 16 submaps. N==8 would create 256.

**Comment by greg7mdp** [comment]
Closing this issue. Please feel free to reopen if you have more questions.
