### ISSUE TITLE
Segfault - multi threads 

### ISSUE THREAD

**Issue by StavrosMar** [greg7mdp/parallel-hashmap#153]
Hi, 

i have noticed that when I have a range for loop on the elements of the map on one thread and another thread that is creating a key ( can be via emplace or operator[] ) , I get segmentation faults. My current workaround is to add a lock (spinlock) between the 2 and it works fine. Map has dynamically allocated objects i.e std::string as key . Can you please confirm what I am doing is supported or it is expected that it is not working because I am iterating over itérators that are probably invalidated when the second thread adds an element ? I can add some sample code when I get some time if you think the behavior is abnormal . Thank you

**Comment by StavrosMar** [comment]
I am using phmap::parallel_flat_hash_map

**Comment by greg7mdp** [comment]
> I am using phmap::parallel_flat_hash_map

Indeed you cannot use iterators in a multi-thread context. If you provide a mutex as the last template parameter., then you can use some extended APIs which are thread-safe, but not any API using iterators.

**Comment by StavrosMar** [comment]
ok, thank you Greg, in that case I might leave the external spinlock in place, thank you I will close the issue
