### ISSUE TITLE
system gtest

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [greg7mdp/parallel-hashmap#154]
Could you provide a way to not download gtest and use the system one?

**Comment by greg7mdp** [comment]
I'm no cmake expert. Would you have a suggestion on how to do this?

**Comment by smoe** [comment]
I also ran into this, which is a precondition to get  it into Linux distributions. To avoid the download I removed the dependency of the test binaries, but I then get link errors and I am no gtest expert :)

**Comment by greg7mdp** [comment]
OK, I'm fixing this now.

**Comment by greg7mdp** [comment]
@smoe please try the latest phmap version... it should work now.
