### ISSUE TITLE
How fast is the parallel-hashmap compared to other concurrent hashmaps?

### ISSUE THREAD

**Issue by mdimura** [greg7mdp/parallel-hashmap#16]
How fast is the parallel-hashmap compared to other concurrent hashmaps, e.g. [libcuckoo](https://github.com/efficient/libcuckoo), TBB, [folly](https://github.com/facebook/folly/blob/master/folly/concurrency/ConcurrentHashMap.h), [junction](https://github.com/preshing/junction), etc?

**Comment by greg7mdp** [comment]
If you are accessing a shared hash map in multiple threads, and the hash map access time is the bottleneck, you might want to try TBB or junction. Otherwise the newer hash maps like folly, phmap, abseil, ... have similar performance in real life situations. Using any one of these should be fine.
