### ISSUE TITLE
Consistency of different versions of API

### ISSUE THREAD

**Issue by BiteTheDDDDt** [greg7mdp/parallel-hashmap#162]
In `1.33`, we can use if_contains like `mp.if_contains(key, [&value](const auto& v) { value = v; });`.
When I update phmap to `1.35`, I meet compile fail, I should change the code to `mp.if_contains(key, [&value](const auto& v) { value = v.second; });`. 
Does we have any solution or plan to support the first case? I'm willing try to do some compatibility support.

**Comment by greg7mdp** [comment]
I'm sorry, there is no plan to support the old API. Is it not possible to update the code using the API?

**Comment by BiteTheDDDDt** [comment]
> 

Thanks for your reply, the reason is good. I will try to update my code. :)
