### ISSUE TITLE
Iterator invalidation

### ISSUE THREAD

**Issue by valos12** [greg7mdp/parallel-hashmap#17]
Are iterators still invalidated after each insert?

**Comment by greg7mdp** [comment]
yes, just like for std::unordered_map.

**Comment by valos12** [comment]
Have you thought of proposing to STL implementers to replace the current unordered containers with what you provide? I haven't seen another custom hash table so well aligned with what the stl currently offers in terms of interface. Not to say that it is extremely fast with something like robin hood hash. 
    Pe duminică, 21 iulie 2019, 23:45:37 EEST, Gregory Popovitch <notifications@github.com> a scris:  
 
 
yes, just like for std::unordered_map.

**Comment by greg7mdp** [comment]
There are some specifications for the std::unordered_map, that almost nobody relies upon, which make phmap not a fully conforming replacement. For example:

> Elements in an unordered associative container are organized into buckets, keys with the same hash will end up in the same bucket. The number of buckets is increased when the size of the container increases to keep the average number of elements in each bucket under a certain value.

from: [cppreference](https://en.cppreference.com/w/cpp/named_req/UnorderedAssociativeContainer)

**Comment by valos12** [comment]
Jesus. Why would they still keep this?
