### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [greg7mdp/parallel-hashmap#170]
👋  it looks like the latest version got marked with 1.3.8 (vs 1.36 before), let me know if that is intentional. Thanks!

![image](https://user-images.githubusercontent.com/1580956/194729036-c1c4f12d-67fe-495e-99a9-4fa7ca06d0ff.png)

**Comment by greg7mdp** [comment]
Yes, that was intentional, I switched to semantic versioning scheme, thanks for asking @chenrui333 !

**Comment by chenrui333** [comment]
Cool, thanks!
