### ISSUE TITLE
Can't compile on C++ latest

### ISSUE THREAD

**Issue by OutTheShade** [greg7mdp/parallel-hashmap#171]
When trying to compile my project which includes "phmap.h", I get this error unless if I use C++ latest. Is this something from my end, or do I wait until a change is made to the library? Compiles fine if I use C++ 20.

`\Dependencies\parallel_hashmap\phmap_base.h(108,50): error C4996: 'std::aligned_storage<_Len,_Align>': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to acknowledge that you have received this warning.`

**Comment by OutTheShade** [comment]
This only happens after updating Visual Studio to the latest version

**Comment by greg7mdp** [comment]
Hey, thanks for reporting this @OutTheShade. Issue should be fixed in the current version.
