### ISSUE TITLE
Modules Support?

### ISSUE THREAD

**Issue by OutTheShade** [greg7mdp/parallel-hashmap#178]
Have the developers of this library considered porting them to modules? Modules will be heard of a lot more in the future and are a great feature. Though you can't really use modules with phmap at this time cause it leads to some bugs. Really love this library and was hoping module support or the headers being ported to modules was being considered. Thanks.

**Comment by greg7mdp** [comment]
Hi @OutTheShade ,

One of the requirements I set for myself is for this library to require only C++11, so I don't think I'll try to add support for modules.
However, I also have a C++20 version, the [gtl](https://github.com/greg7mdp/gtl) library. It contains all the same classes as phmap, and more. I think eventually I'll add support for modules to it, but not right now as I'm starting a new job and very busy.

**Comment by OutTheShade** [comment]
Thanks for the response. I completely understand, good luck on your new job!
