### ISSUE TITLE
Returns `void` from the `erase(iterator)` overload

### ISSUE THREAD

**Issue by heyfey** [greg7mdp/parallel-hashmap#179]
Hi @greg7mdp,

https://github.com/greg7mdp/parallel-hashmap/blob/d676385fb408da3dac3c14f3f62ac0197e24370c/parallel_hashmap/phmap.h#L4703
https://github.com/greg7mdp/parallel-hashmap/blob/d676385fb408da3dac3c14f3f62ac0197e24370c/parallel_hashmap/phmap.h#L4768

Are these typos? I believe it is `_erase(iterator)` that returns `void`

**Comment by greg7mdp** [comment]
Hi @heyfey , you are right, these were typos, I just fixed them (see this [commit](https://github.com/greg7mdp/parallel-hashmap/commit/c36739b79ff1dd506708de251c43e8c778da2c00)). Thanks for the report!
