### ISSUE TITLE
reserve and capacity not matching

### ISSUE THREAD

**Issue by gviot** [greg7mdp/parallel-hashmap#18]
Hello,
I encountered an issue with reserve and capacity.
I am using parallel flat hash map.

When calling reserve(X),  The following call to capacity() does not seem to return X or even anything close, I could see why it would be different because of the way the hashmap is implemented, but the difference seems pretty big and as a result a call to capacity() seem useless and dangerous.

My use case was iterating a bunch of images to collect statistics and color info.
For each image I was doing a map.reserve(std::max(map.capacity(), image.size()) to make sure the map's capacity was at least the current image's number of pixels.
The program ended up trying to allocate several GBs of memory and ended up crashing pretty fast. Without the reserve line, memory usage peaks at like 350 MB.

Is this supposed to be this way ?

**Comment by greg7mdp** [comment]
Thanks for the report. I'll look into it. Can you give me the types stored in the parallel_flat_hash_map?
Also an idea of what kind of image.size() we are talking about?

**Comment by gviot** [comment]
the biggest image is 1920 x 1080 so about 2M size(), on the debugger I looked at one random iteration, the image.size() was about 900K and map's capacity was already returning more than 33M.
The types are a small color struct as seen in the following snippet and unsigned 64 bit int. The pair type is std::pair<const Color, uint64_t>. I have also provided my hash implementation
```
struct Color { uint8_t r, g, b; };
namespace std
{
	inline void hash_combine(std::size_t& seed) { }

	template <typename T, typename... Rest>
	inline void hash_combine(std::size_t& seed, const T& v, Rest... rest) {
		std::hash<T> hasher;
		seed ^= hasher(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
		hash_combine(seed, rest...);
	}

	template <>
	struct hash<Color>
	{
		std::size_t operator()(const Color& c) const
		{
			std::size_t result = 0;
			hash_combine(result, c.r, c.g, c.b);
			return result;
		}
	};
}
```
Also probably not related to the issue, but I should point out that I am using my game engine's custom allocator with the map, the rest of the template arguments are the default values of the library.

**Comment by greg7mdp** [comment]
I have made a fix, Please try the new version and let me know how it works.
Depending on how many pixels are the same color, the full image size may still be more than what is required.

**Comment by gviot** [comment]
I had a feeling it was a bit better when first tested the fix, but I still have the issue.
I tried to remove the unnecessary things from my code and test just the loop with the reserve call, here is what I found:
--
First iteration/image:
image size: 789600 
map_capacity: 0
--
Second iteration
image_size: 418400
map_capacity: 1048560
--
Third iteration
image_size: 837600
map_capacity: 2097136

From this point the call to map.reserve(map.capacity()) seems to double the capacity every time

**Comment by greg7mdp** [comment]
> From this point the call to map.reserve(map.capacity()) seems to double the capacity every time

Yes, that is expected, because the reserve(n) will add n/7 to the size and then align the size to the roughly the next-power-of-two.

I would suggest that you do: `map.reserve(std::max(map.size(), image.size())`

**Comment by gviot** [comment]
Alright, the behaviour is a little surprising since stl containers that expose reserve and capacity will do nothing if trying to reserve a capacity that is already available. But the explanation makes sense, so I will use size instead.
Thanks

**Comment by greg7mdp** [comment]
capacity() is an extension here, std::unordered_map doesn't have a capacity() api, so it is probably better that you use size() anyways.
Also, I imagine that you use reserve() because you are concerned about speed. If that is the case, it would probably be faster to go over all images and find out the largest size in pixels, and then do a reserve of the map only once at the beginning. It would avoid doing map rehash() that can occur when doing a reserve.
