### ISSUE TITLE
CMake FetchContent not working (linker issues)

### ISSUE THREAD

**Issue by mortbopet** [greg7mdp/parallel-hashmap#182]
I haven't been able to track down an issue on my side, and i've been able to use other projects through `FetchContent` successfully. As far as i can tell, the `FetchContent` stuff is not being tested in CI in this repo, so a regression might have snuck in.

The test project setup is:

main.cpp
```c++
int main() { return 0; }
```

CMakeLists.txt
```CMake
project(phtest)

include(FetchContent)
FetchContent_Declare(
    parallel-hashmap
    GIT_REPOSITORY https://github.com/greg7mdp/parallel-hashmap.git
    GIT_TAG        v1.3.8 # adjust tag/branch/commit as needed
)
FetchContent_MakeAvailable(parallel-hashmap)

add_executable(phtest main.cpp)
target_link_libraries(phtest PRIVATE parallel-hashmap)
```

Fails with:
```
/usr/bin/ld: cannot find -lparallel-hashmap
collect2: error: ld returned 1 exit status
CMakeFiles/phtest.dir/build.make:96: recipe for target 'phtest' failed
make[2]: *** [phtest] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/phtest.dir/all' failed
make[1]: *** [CMakeFiles/phtest.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by greg7mdp** [comment]
`parallel-hashmap` is a header only library, so try using `INTERFACE` instead of `PRIVATE` in your `target_link_libraries` line.

**Comment by mortbopet** [comment]
I'll give that a shot - in that case, https://github.com/greg7mdp/parallel-hashmap/blob/master/CMakeLists.txt#L16 probably ought to be modified.

**Comment by greg7mdp** [comment]
Actually, never mind, this is an issue in phmap. Will look into it!

**Comment by greg7mdp** [comment]
You don't need the `target_link_libraries` line.
