### ISSUE TITLE
Simple emplace function crashed during concurrent execution

### ISSUE THREAD

**Issue by Jiboxiake** [greg7mdp/parallel-hashmap#186]
Hello, I'm having several worker threads concurrently executing the following line of code with the following data structure:
```
phmap::parallel_flat_hash_set<Shortest_Distance_Query, Query_Hash>;
bool insert_query(Shortest_Distance_Query query){
        return unique_queries.emplace(query).second;
    }
```
But then it throws an error: 
```
road_network_routing: /scratch1/zhou822/road_network_routing/./WSPD_Preprocessing/../parallel_hashmap/phmap.h:2253: void phmap::priv::raw_hash_set<Policy, Hash, Eq, Alloc>::set_ctrl(size_t, phmap::priv::ctrl_t) [with Policy = phmap::priv::FlatHashSetPolicy<Shortest_Distance_Query>; Hash = Query_Hash; Eq = phmap::EqualTo<Shortest_Distance_Query>; Alloc = std::allocator<Shortest_Distance_Query>; size_t = long unsigned int; phmap::priv::ctrl_t = signed char]: Assertion `i < capacity_' failed.
```
Do you think if I'm doing something wrongly?

**Comment by greg7mdp** [comment]
I can't really tell from this information. I would need more actual code, even better a sample program reproducing the issue. `emplace` returns a `pair<iterator,bool>`. The iterator is not safe to use in a multi-threaded environment, but the `bool` should be.

**Comment by Jiboxiake** [comment]
I see, thank you. I'm having some strange errors when defining my parallel hash set on my customized class. Will let you know if it gets resolved. Thanks.

**Comment by greg7mdp** [comment]
Closing the issue now, please reopen if needed.
