### ISSUE TITLE
Linter warning `-Wambiguous-reversed-operator` when using `it != o.end()`

### ISSUE THREAD

**Issue by midrare** [greg7mdp/parallel-hashmap#188]
Comparing iterators is giving a linter warning, `ambiguous-reversed-operator`. Windows 11, `clang-tidy` 16.0.1.

**code to reproduce**  
```c++
phmap::btree_multimap<int, int> foo;
for (auto it = foo.begin(); it != foo.end(); it++) {
}
```

![screen](https://user-images.githubusercontent.com/59168253/231648026-9a7c56b1-4fde-4b19-8fcd-cd586316cb6c.png)

**Comment by greg7mdp** [comment]
I can seem to reproduce this warning on linux (ubuntu 22.04). I've tried with clang-tidy 17. Would you have a suggestion for fixing this?
