### ISSUE TITLE
Recommendation for  deserializing a large hashmap? 

### ISSUE THREAD

**Issue by andreirajkovic** [greg7mdp/parallel-hashmap#19]
Thank you Greg for this awesome contribution, I am finding it quite useful for my application. 

I plan to generate a very large hashmap with bitsets as the key and integers as the value. The size of the hashmap will be 10GB when serialized to binary. It might also  be important to note that the hashmap will not be modified after generation; purely used for look-up purposes. 

I went ahead and serialized a 1GB flat hashmap using cereal and that took about 10 minutes, while it took about 20 minutes to deserialize.

From what I could gather, hashmaps are slow to deserialize due to the fact they need to repopulate the entire map again from scratch (or so I've been told).

To mitigate the slow deserialization process I was thinking to split the hashmap up and by some means parallelize the process of deserialization. Or maybe pre-allocating the memory necessary for the hashmap will speed things up. I am not really sure.

I look forward to receiving your response.

**Comment by greg7mdp** [comment]
Hi Andre,

Thanks for the kind words.  Can you give me the cereal code that you use to serialize/deserialize your map. Also precisely which map type are you using? I think we may be able to improve the speed a lot.

> Indeed when deserializing, if you know the map size, doing a reserve() will help.

**Comment by andreirajkovic** [comment]
Build the hashmap
`#include <iostream>
#include <bitset>
#include <string>
#include <cinttypes>
#include "parallel_hashmap/phmap.h"
#include "cereal/types/unordered_map.hpp"
#include "cereal/types/bitset.hpp"
#include "cereal/types/memory.hpp"
#include "cereal/archives/binary.hpp"
#include <fstream>
#include <random>

using phmap::flat_hash_map;
using namespace std;

int main()
{
    //  initialize the keys
		bitset<42> set8;
		bitset<42> set9;
		bitset<42> set10;
		set8[2] = 1;
		set9[3] = 1;
		set10[5] = 1;
    // Create an unordered_map of three strings (that map to strings)
    flat_hash_map<bitset<42>, int> table = 
    {
        { set8 ,  1},
        { set9 , 2},
        { set10,  3}
    };
 		

    // Iterate and add keys and values 
    random_device dev;
    mt19937 rng(dev());
    uniform_int_distribution<mt19937::result_type> dist6(0,1);
    for (int i=1; i < 100000000; ++i){
    	for (int j=0; j<42; ++j){
    		set8[j] = dist6(rng);
    	}
    	table[set8] = i;
    }
    

    // cerealize and save data
    ofstream os("out.cereal", ios::binary);
    cereal::BinaryOutputArchive archive(os);
    archive( table );

    return 0;
}`

Deserialize 
`#include <iostream>
#include <bitset>
#include <string>
#include <cinttypes>
#include "parallel_hashmap/phmap.h"
#include "cereal/types/unordered_map.hpp"
#include "cereal/types/bitset.hpp"
#include "cereal/types/memory.hpp"
#include "cereal/archives/binary.hpp"
#include <fstream>
#include <random>

using phmap::flat_hash_map;
using namespace std;

int main()
{

   // deserialize
   {
      ifstream is("out.cereal", ios::binary);
      cereal::BinaryInputArchive archive_in( is );

      flat_hash_map<bitset<42>, int> table;
      archive_in( table );             // deserialize from file out.cereal into variable
        // Iterate and print keys and values 
        for (const auto& n : table) 
        cout << n.first << " : " << n.second << "\n";
   }

   return 0;
}`

**Comment by greg7mdp** [comment]
Awesome! Let me play with this a little bit. Will you always serialize/deserialize on the same machine/os type?

**Comment by andreirajkovic** [comment]
Yes, I am operating under that assumption. So hopefully no need to add the extra overhead :)

**Comment by atom-moyer** [comment]
Hey,

This is the cerealization code that I use for getpy. I think it may be helpful.

‘’’
    void dump ( const std::string & filename ) {
        std::ofstream stream ( filename , std::ios::binary );
        cereal::BinaryOutputArchive oarchive ( stream );

        for ( auto & key_value : __dict ) {
            oarchive(key_value);
        }
    }


    void load ( const std::string & filename ) {
        std::ifstream stream ( filename , std::ios::binary);
        cereal::BinaryInputArchive iarchive ( stream );

        std::pair<Key, Value> in_key_value;
        while ( stream.peek() != EOF ) {
            iarchive(in_key_value);
            __dict.emplace(in_key_value.first, in_key_value.second);
        }
    }
‘’’

**Comment by andreirajkovic** [comment]
Thanks for that sample cerealization code! I'll def. take a look into it.

**Comment by greg7mdp** [comment]
Hi Andre,

I am surprised that it takes 20 minutes to deserialize a 1GB file. On my machine it takes less than 2 minutes, even using a slow spinning disk. See the example I added `serialize.cc`.

Also, it is almost 5x faster (24s) if you save the size, and do a reserve before deserializing, as long as you get the new version of phmap.h (I have made a small change). Code is in `serialize.cc`. Basically:

serialize:
```
            archive(table.size());
            archive(table);
```

deserialize:
```
            size_t table_size;

            archive_in(table_size);
            table.reserve(table_size);
            archive_in(table); 
```

**Comment by andreirajkovic** [comment]
Thank you Gregory, 

I'll  will check that out right now!

**Comment by andreirajkovic** [comment]
I went ahead and tested this implementation on osx and a debian architecture. Both are giving me around 8 minutes to generate the table ~2 minutes and 40 seconds to serialize and 3 minutes to deserialize. I think that the example code might have a little slip up in it.

```cpp
printf("%s: %.3fms\n", name, (int)elapsed / 1000.0f);
```

should be

```cpp
printf("%s: %.3fms\n", name, (int)elapsed);
```
 I think I might be trying to spin gold from silk here and get FPGA type of speeds...

**Comment by greg7mdp** [comment]
Yes you are right in the example I meant s not ms.

I am surprised that it takes so long for you. Here are the times I get on windows (using vs2019, intel i7-7700K). 

![image](https://user-images.githubusercontent.com/1496907/62000035-31e52b80-b09c-11e9-8153-3d16e4d69dff.png)

I assume you are building with optimization (-O3) and that you have enough ram to not swap.

**Comment by andreirajkovic** [comment]
Yes! Adding -O3 solved it! Thank you so much for your help!

**Comment by greg7mdp** [comment]
Great, glad it works better. If the deserialization speed is critical for your application, indeed we can probably speed it up some more with multithreading as you originally suggested.

**Comment by andreirajkovic** [comment]
That would great if we could implement some multithreading, as loading the hashmap is currently my bottleneck. Though, would it be possible to use something like mmap() to instantaneously load the hashmap?

**Comment by greg7mdp** [comment]
I'll have to think about this. Please give me a few days as I won't be able to work on it today. Thanks - greg

**Comment by d4tocchini** [comment]
mmap'ing would be killer, with shared r/w safety from compare-and-swaps (or phmap's mutex's?) then multiple processes/threads could share persistable phmaps without the (de)serializing hit (as long as inserted data isnt pointer madness).  [EMS](http://syntheticsemantics.github.io/ems/Docs/index.html) (Extended Memory Semantics) is a shining example of such, [see src](https://github.com/SyntheticSemantics/ems/blob/8a3e49bacf7bc034310cb6e3d91a6ea9539bc8e3/src/ems.cc#L888).  LMDB takes this idea all the way to ACID compliant DB.

@greg7mdp, how feasible is this?  a matter of allocation rigging or rabbit hole?

**Comment by andreirajkovic** [comment]
Yes I did mean that the actual file size doubles, sorry for the ambiguity. I take it that a lot more information needs to be stored to make it load quickly. 

And using parallel_flat_hash_map loaded in no time! I loaded a 70gb map in a minute!!! 

Are there any caveats to using parallel_flat_hash_map vs flat_hash_map?

**Comment by greg7mdp** [comment]
> Are there any caveats to using parallel_flat_hash_map vs flat_hash_map?
Not that I can think of. It will reduce the memory requirements when building the map, 

Are you building the map once, and then deserializing it many times? Is that is the case, you may want to try this:

```
using MapType = phmap::flat_hash_map<std::bitset<42>, unsigned long>;
MapType table;

// build map
...

table.resize((size_t)(table.size() * 1.1f))
table.dump();
```

**Comment by andreirajkovic** [comment]
I can't think of a situation where I would be deserializing the map multiple times. But I will keep that in mind.

**Comment by greg7mdp** [comment]
Sounds good, should I close the issue?

**Comment by andreirajkovic** [comment]
Yes!  Thank you both @greg7mdp and @gtarcoder !
