### ISSUE TITLE
Conan package update for the last version v1.3.11?

### ISSUE THREAD

**Issue by FrancoisDn** [greg7mdp/parallel-hashmap#190]
Hi, Is there some plan to publish the latest version of parallel-hashmap to conan.io? (https://conan.io/center/parallel-hashmap)
I like is library, very performance and straightforward to use. When available, I prefer to use conan to integrate to my project.

**Comment by greg7mdp** [comment]
I was planning on updating to conan last weekend, but when I tried to use the new conan 2 version it didn't work at all. What conan version are you using?

**Comment by FrancoisDn** [comment]
Oh, ok, great to know. I use conan 1.59.0 because I had some problem with conan 2.0 and CMake integration.

**Comment by greg7mdp** [comment]
I'll try again with the 1.xx version. Thanks for using parallel-hashmap!

**Comment by greg7mdp** [comment]
Conan package was just updated to the latest phmap version! Yeah. See [here](https://github.com/conan-io/conan-center-index/pull/17291#event-9127234273)
