### ISSUE TITLE
shared_mutex?

### ISSUE THREAD

**Issue by vinniefalco** [greg7mdp/parallel-hashmap#2]
What happens if I want to use a `shared_mutex` instead of a regular mutex? I am thinking to take a shared lock on reads, and the exclusive lock on insertions. Use-case:
https://github.com/vinniefalco/BeastLounge/blob/8647895a3d691f7e9b7b3f5fbcfee6ba3f987c19/server/channel_list.cpp#L52

I suppose I could build my own container that is specific to my data types (and avoid templates, to get faster builds) and use the non-synchronized hashmap from this library as a building block.

**Comment by greg7mdp** [comment]
I was thinking that instead of providing a mutex as a template parameter, I could allow for a class that has two lock/unlock methods, so you'd be able to use for example:
```
class StdLockable {
public:
    void lock()          { m_.lock(); }
    void unlock()        { m_.unlock(); }
    void lock_shared()   { m_.lock(); }
    void unlock_shared() { m_.unlock(); }

private:
    std::mutex m_;
};

class SharedLockable{
public:
    void lock()          { m_.lock(); }
    void unlock()        { m_.unlock(); }
    void lock_shared()   { m_.lock_shared(); }
    void unlock_shared() { m_.unlock_shared(); }

private:
    boost::shared_mutex m_;
};
```

Internally the phmap would use lock_shared for the red APIs and lock for the mutable ones.

**Comment by greg7mdp** [comment]
> For example, I would consider the normal hashmap interface to be "sufficient flexible" if it is possible to build a parallel hashmap from it with no loss of performance, using only the public interfaces (is it?)

No it isn't. For example there is no way to avoid recomputing the hash in the internal submaps using the std interface.

**Comment by vinniefalco** [comment]
> there is no way to avoid recomputing the hash in the internal submaps using the std interface.

Then I would explore this direction. Is there a clean way to provide an interface that avoids the recomputation of the hash?

**Comment by greg7mdp** [comment]
Well, for complicated use cases as you suggest, it is better to keep the locking separate. I don't really see the use case where the additional interface you suggest would be useful.

However, I still think that internal locking can be convenient for simple use cases, and that I need to support shared_locks.

**Comment by vinniefalco** [comment]
>  I still think that internal locking can be convenient for simple use cases, and that I need to support shared_locks.

Okay. What about upgrade locks then? On insertion, acquire the shared lock to determine if the element already exists, and then if not, upgrade the shared lock to an exclusive lock to modify the map.

**Comment by greg7mdp** [comment]
So the sequence is something like this?
```
m.lock_upgrade();
find();
if (present)
{
    m.unlock_upgrade();
    return;
}
m.lock();
insert_item();
m.unlock();
m.unlock_upgrade(); // not sure about that last one
```

**Comment by vinniefalco** [comment]
The **UpgradeLockable** concept is a Boost extension, you can read about it here:
https://www.boost.org/doc/libs/1_69_0/doc/html/thread/synchronization.html#thread.synchronization.mutex_concepts.upgrade_lockable

I bring up the upgrade lock approach not because I am suggesting that you should implement it, but to show how there are uncountably many different approaches, and tying the parallel hashmap to one solution will necessarily disadvantage others.

**Comment by greg7mdp** [comment]
I think I can support the upgrade lock cleanly as well. This is a pretty general concept. You can get a shared lock, a unique lock, and if necessary you can upgrade a shared lock to a unique lock.

**Comment by greg7mdp** [comment]
Hi Vinnie,

The current version uses a more flexible locking mechanism which should support boost::shared_mutex and boost::upgrade_mutex, although I haven't tested with these yet. The only location internally where we actually upgrade the mutex, though, is in `erase` (so we don't unique_lock if we attempt to erase a value that is not present).
In order for this to work, the boost mutex headers have to be included before phmap.h.

**Comment by greg7mdp** [comment]
Hi Vinnie, I validated the use of the boost::upgrade_mutex in phmap (which is the same class as shared_mutex), so closing the ticket. Feel free to ask if you have further questions.
