### ISSUE TITLE
Computing std::hash once per key for the hash_bench example

### ISSUE THREAD

**Issue by marioroy** [greg7mdp/parallel-hashmap#201]
Ah, I just realized the hash_bench example today. Thank you for the small demonstration. The following is not an issue but mainly curiosity. I tried [hash_bench2.cc](https://gist.github.com/marioroy/33b1ec5688e0c84a00a669e43993170c), computing `std::hash` once per key.

```text
hash_bench   7.016 seconds
hash_bench2  2.813 seconds

lkfm: 7360
elkl: 7720
pnjj: 7860
mloo: 7860
iokk: 7650
```

Seeing 2.5x is mind-boggling to me. So much so that I will try the same thing for the [Long List is Long](https://gist.github.com/marioroy/c76c1a2f65abfd9eb9bad186688f228d) demonstration and report back.

**Comment by greg7mdp** [comment]
That's not really surprising, the whole purpose of the test was to test the speed of the hash method. I wanted to try [polymur-hash](https://github.com/orlp/polymur-hash) - the test is in my [gtl](https://github.com/greg7mdp/gtl) repo which is equivalent to phmap except that it requires c++17.

BTW your test has an incorrect comparison function, you should compare the `str` not the `hash`.

I'm curious to see how you would use this in `llil`. `phmap` has some APIs that take the hash value if precomputed (look for `with_hash`).

**Comment by marioroy** [comment]
Oh,... The mind-boggling part was not so much about the variant running faster, but the possibility of Long List is Long able to run faster. And the joy in trying things.

> BTW your test has an incorrect comparison function, you should compare the str not the hash.

I will try both ways for the LLIL demonstration. I do not understand why one cannot use the hash value as it's tied to the key.  Am I assuming wrongly for the hash value to be unique per key?

> `phmap` has some APIs that take the hash value if precomputed (look for `with_hash`)

I saw them at a quick glance but did not realize the possibility. I will try. Thank you.

**Comment by marioroy** [comment]
I commented out the if statement and the output matches between `hash_bench` and `hash_bench2`.
```c++
    // if (++cnt == 6) break;
```

**Comment by marioroy** [comment]
Please disregard my hash_bench2 demonstration. I see now the purpose of the `hash_bench` example. To compare `std::hash` against `polymur-hash`.

**Comment by marioroy** [comment]
I'm closing the issue. The hash_value is computed one time only, already. It has been an interesting journey. Again, thank you for the hash map library.

**Comment by marioroy** [comment]
I compared equal `l.str == r.str` and `l.hash == r.hash`. The output is the same. Regardless, I changed the gist to `l.str == r.str` per your suggestion.

```text
hashbench:  7.016 seconds
hashbench2 l.str == r.str:  4.318 seconds
hashbench2 l.hash == r.hash:  2.813 seconds
```

**Comment by marioroy** [comment]
The motivation for doing this was nothing more than curiosity or wondering if `std::hash` is computed more than once per key.  And if so, how much time saved if computed one time. I saw no measurable time difference for llil. No issue either for doing equal `return l.hash == r.hash;`. The output is the same.

```diff
128a129,134
> using hash_type        = std::size_t;
> 
> struct S {
>    str_type  str;
>    hash_type hash;
> };
132,135c138,141
<    str_type, int_type,
<    phmap::priv::hash_default_hash<str_type>,
<    phmap::priv::hash_default_eq<str_type>,
<    phmap::priv::Allocator<phmap::priv::Pair<const str_type, int_type>>,
---
>    S, int_type,
>    decltype( [](const S& k) { return k.hash; } ),
>    decltype( [](const S& l, const S& r) { return l.hash == r.hash; } ),
>    phmap::priv::Allocator<phmap::priv::Pair<const S, int_type>>,
226a233,235
>             hash_type h = std::hash<std::basic_string_view<char>>{}(
>                std::basic_string_view<char>{ reinterpret_cast<const char*>(&s[0]), s.size() }
>             );
229c238
<                s,
---
>                S{ s, h },
236c245
<                   ctor(std::move(s), count);
---
>                   ctor(S{ std::move(s), h }, count);
326c335
<    for (auto const& x : map) propvec.emplace_back(x.first, x.second);
---
>    for (auto const& x : map) propvec.emplace_back(x.first.str, x.second);
```

It has been a lot of fun trying things and learned a lot.

**Comment by greg7mdp** [comment]
> Am I assuming wrongly for the hash value to be unique per key?

Yes, there is no guarantee that this would be the case. Maybe this is the case here because we have a small number of different strings, but again this is not a given.

**Comment by marioroy** [comment]
Thank you for the extra clarity on why not to do that. In the end, I omitted the change altogether.

I came across `with_submap` inside the `tests` folder. That is helpful in llil to iterate the submaps in parallel (phmap to vector).

### Before:
```c++
   // Store the properties into a vector
   vec_str_int_type propvec; propvec.reserve(8 + map.size());
   for (auto const& x : map) propvec.emplace_back(x);
   map.clear();
```

### After:
```c++
   // Store the properties into a vector
   vec_str_int_type propvec; propvec.reserve(8 + map.size());

   #pragma omp parallel for schedule(static, 1) num_threads(4)
   for (size_t i = 0; i < map.subcnt(); ++i) {
      map.with_submap(i, [&](const map_str_int_type::EmbeddedSet& set) {
         if (set.size()) {
            vec_str_int_type v; v.reserve(8 + set.size());
            for (auto& p : set) v.emplace_back(p);
            #pragma omp critical
            propvec.insert(propvec.end(), v.begin(), v.end());
         }
      });
   }

   map.clear();
```

The [llil4map.cc](https://gist.github.com/marioroy/c76c1a2f65abfd9eb9bad186688f228d) code is final.

**Comment by marioroy** [comment]
The [emhash](https://github.com/ktprime/emhash) entry recently appeared under "Explore repositories" on my GitHub page. Like `flat_hash_map`, `emhash` is not thread-safe. So, I thought about having the application handle locking including sub maps. Doing this gave me a new appreciation for `parallel_flat_hash_map`.

1. [llil4map.cc](https://gist.github.com/marioroy/c76c1a2f65abfd9eb9bad186688f228d)
2. [llil4hmap.cc](https://gist.github.com/marioroy/3c3d91eabbde4adeb5ac6543929d3d92)
3. [llil4emh.cc](https://gist.github.com/marioroy/d82e9eb1a8ed6c7e28868c7ba1357bec)

`emhash` performs similarly to `flat_hash_map`, but flies when processing input containing duplicate keys. I ran with 1 thread for get_properties. Behind the scene, it consumes 4 threads during hashmap to vector and sorting consumes max 24 threads.

### Running 1 thread (52 input files; 26 * 2):

```text
$ NUM_THREADS=1 ./llil4map in/biga* in/biga* | cksum
llil4map (fixed string length=12) start
use OpenMP
use boost sort
get properties        43.310 secs
phmap to vector        0.290 secs
vector stable sort     0.687 secs
write stdout           1.608 secs
total time            45.897 secs
3291503642 712085184
```

```text
$ NUM_THREADS=1 ./llil4hmap in/biga* in/biga* | cksum
llil4hmap (fixed string length=12) start
use OpenMP
use boost sort
get properties        33.839 secs
hashmap to vector      0.439 secs
vector stable sort     0.663 secs
write stdout           1.530 secs
total time            36.472 secs
3291503642 712085184
```

```text
$ NUM_THREADS=1 ./llil4emh in/biga* in/biga* | cksum
llil4emh (fixed string length=12) start
use OpenMP
use boost sort
get properties        27.888 secs
emhash to vector       0.293 secs
vector stable sort     0.672 secs
write stdout           1.583 secs
total time            30.438 secs
3291503642 712085184
```

### Running many threads (52 input files; 26 * 2):

```text
$ NUM_THREADS=24 ./llil4map in/biga* in/biga* | cksum
llil4map (fixed string length=12) start
use OpenMP
use boost sort
get properties         3.296 secs
phmap to vector        0.318 secs
vector stable sort     0.671 secs
write stdout           1.540 secs
total time             5.827 secs
3291503642 712085184
```

```text
$ NUM_THREADS=24 ./llil4hmap in/biga* in/biga* | cksum
llil4hmap (fixed string length=12) start
use OpenMP
use boost sort
get properties         3.145 secs
hashmap to vector      0.297 secs
vector stable sort     0.673 secs
write stdout           1.580 secs
total time             5.697 secs
3291503642 712085184
```

```text
$ NUM_THREADS=24 ./llil4emh in/biga* in/biga* | cksum
llil4emh (fixed string length=12) start
use OpenMP
use boost sort
get properties         3.094 secs
emhash to vector       0.219 secs
vector stable sort     0.667 secs
write stdout           1.535 secs
total time             5.516 secs
3291503642 712085184
```

**Comment by marioroy** [comment]
I tried again to better understand few and many duplicate keys running 1 thread.

### Few duplicate keys

```text
$ NUM_THREADS=1 ./llil4map big{1,2,3}.txt | cksum
llil4map (fixed string length=12) start
use OpenMP
use boost sort
get properties         1.841 secs
phmap to vector        0.036 secs
vector stable sort     0.086 secs
write stdout           0.204 secs
total time             2.168 secs
2956888413 93308427
```

```text
$ NUM_THREADS=1 ./llil4hmap big{1,2,3}.txt | cksum
llil4hmap (fixed string length=12) start
use OpenMP
use boost sort
get properties         1.446 secs
hashmap to vector      0.055 secs
vector stable sort     0.074 secs
write stdout           0.211 secs
total time             1.788 secs
2956888413 93308427
```

```text
$ NUM_THREADS=1 ./llil4emh big{1,2,3}.txt | cksum
llil4emh (fixed string length=12) start
use OpenMP
use boost sort
get properties         1.683 secs
emhash to vector       0.041 secs
vector stable sort     0.064 secs
write stdout           0.205 secs
total time             1.994 secs
2956888413 93308427
```

### Many duplicate keys

```text
$ NUM_THREADS=1 ./llil4map big{1,2,3,1,2,3,1,2,3}.txt | cksum
llil4map (fixed string length=12) start
use OpenMP
use boost sort
get properties         5.901 secs
phmap to vector        0.035 secs
vector stable sort     0.086 secs
write stdout           0.210 secs
total time             6.234 secs
3780399956 93308444
```

```text
$ NUM_THREADS=1 ./llil4hmap big{1,2,3,1,2,3,1,2,3}.txt | cksum
llil4hmap (fixed string length=12) start
use OpenMP
use boost sort
get properties         4.529 secs
hashmap to vector      0.055 secs
vector stable sort     0.074 secs
write stdout           0.210 secs
total time             4.869 secs
3780399956 93308444
```

```text
$ NUM_THREADS=1 ./llil4emh big{1,2,3,1,2,3,1,2,3}.txt | cksum
llil4emh (fixed string length=12) start
use OpenMP
use boost sort
get properties         4.069 secs
emhash to vector       0.041 secs
vector stable sort     0.069 secs
write stdout           0.205 secs
total time             4.386 secs
3780399956 93308444
```

Now, I like `phmap::flat_hash_map` as much as `parallel_hash_map`. Ditto for `emhash`. I did not realize there could be a difference depending on whether processing many duplicate keys.

**Comment by greg7mdp** [comment]
> That is helpful in llil to iterate the submaps in parallel (phmap to vector).

It would be more efficient to iterate once (not parallel) through the submaps to get their sizes, so you know exactly where to insert their content in the final (resized) vector, and you don't need the intermediate vector and the double copy.

> So, I thought about having the application handle locking including sub maps. 

Yes, you can certainly do that. It is equivalent to what the `parallel_hash_map` does, it just requires a little extra work.
