### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by bpmckinnon** [greg7mdp/parallel-hashmap#208]
Hi, I've started getting the unused variable warning again when exceptions are disabled.  PR 197 reverted an earlier change to suppress the warning, but I agree that constructing the object is not the greatest.

I've tested out a change that will remove the warning, but also remove the need to have those types defined.

Let me know what you think.

```
#ifdef PHMAP_HAVE_EXCEPTIONS
  #define PHMAP_THROW_IMPL_MSG(e, message) throw e(message)
  #define PHMAP_THROW_IMPL(e) throw e
#else
  #define PHMAP_THROW_IMPL_MSG(e, message) do { (void)(message); std::abort(); } while(0)
  #define PHMAP_THROW_IMPL(e) std::abort()
#endif
}  // namespace

static inline void ThrowStdLogicError(const std::string& what_arg) {
  PHMAP_THROW_IMPL_MSG(std::logic_error, what_arg);
}
static inline void ThrowStdBadFunctionCall() {
  PHMAP_THROW_IMPL(std::bad_function_call());
}
```

**Comment by greg7mdp** [comment]
Sounds good, thanks for the great suggestion. I'll do `#define PHMAP_THROW_IMPL(e) throw e()` though to delay the construction.

**Comment by bpmckinnon** [comment]
Thanks!
