### ISSUE TITLE
Release memory after shrinking

### ISSUE THREAD

**Issue by benstadin** [greg7mdp/parallel-hashmap#236]
As far as I understand Google's sparse hash map maintains a low memory footprint by deallocation memory after a certain threshold. Does parallel-hashmap provide a similar feature in order to release memory when the map size is reduced?

**Comment by greg7mdp** [comment]
No, it doesn't. What is your exact use case?
If you want to use as little memory as possible, I recommend using [sparsepp](https://github.com/greg7mdp/sparsepp).

**Comment by benstadin** [comment]
I have multiple maps which independently grow and shrink in size during the lifetime of the application. This application runs multiple days and thus the overall memory required by all maps is very high.

**Comment by benstadin** [comment]
Does it actively free memory when resizing?

**Comment by marioroy** [comment]
I recall `map.clear()` releasing the memory. This stopped working and unsure if occurred around PR #205. So now, the memory is not reclaimed at the OS level until the application has terminated.

**Comment by marioroy** [comment]
I reverted a little bit and now see memory reclaimed.

```diff
diff --git a/parallel_hashmap/phmap.h b/parallel_hashmap/phmap.h
index d9a5b7b..1ac94c1 100644
--- a/parallel_hashmap/phmap.h
+++ b/parallel_hashmap/phmap.h
@@ -1265,7 +1265,9 @@ public:
     PHMAP_ATTRIBUTE_REINITIALIZES void clear() {
         if (empty())
             return;
-        if (capacity_) {
+        if (capacity_ > 127) {
+            destroy_slots();
+        } else if (capacity_) {
            PHMAP_IF_CONSTEXPR((!std::is_trivially_destructible<typename PolicyTraits::value_type>::value ||
                                std::is_same<typename Policy::is_flat, std::false_type>::value)) {
                 // node map or not trivially destructible... we  need to iterate and destroy values one by one
```

My apologies if this is met for a new issue request. I wish map.clear() accepted a boolean `map.clear(true)` to do the prior behavior or destroy slots.

**Comment by greg7mdp** [comment]
To guarantee that a map's memory use is cleared, you can swap it with a temporary map, for example:

```c++
MyMap map;
map.emplace(....);
...
MyMap().swap(map); // swap map with an empty temporary, which is immediately destroyed
```

**Comment by greg7mdp** [comment]
> Does it actively free memory when resizing?

@benstadin yes it does.
