### ISSUE TITLE
hash_multimap

### ISSUE THREAD

**Issue by ExeVirus** [greg7mdp/parallel-hashmap#240]
Hello, great set of maps, and hash maps. Love using them as often as possible.

Realized today you don't have a hash_multimap, but do have a btree_multimap. I could see a lot of value in the node-based hash multimap (doubtful the flat version is useful, as each bucket is probably larger than 100 bytes).

Is there anything stopping this library from having such a map?

**Comment by greg7mdp** [comment]
Hi @ExeVirus , thank you for the kind words. You are right, there could be a hash_multimap, but it would require some development effort that I just haven't done yet, and frankly I don't think I'll do anytime soon as I'm very busy at work these days.
