### ISSUE TITLE
about a concurrency operation issue

### ISSUE THREAD

**Issue by littledoglily** [greg7mdp/parallel-hashmap#248]
"I have a background thread which consumes Kafka messages and then writes them into a parallel_flat_hash_map. Other threads execute find operations. I really want to know if the parallel_flat_hash_map must be protected by a mutex. In our system, we define the map like this: using LocalMap = phmap::parallel_flat_hash_map<uint64_t, std::array<float, N>>, which uses the default NullMutex, and we have not experienced any core dumps or segmentation faults.

However, in the README, I found the following statement: 'If a single hash table is being written to by one thread, then all reads and writes to that hash table on the same or other threads must be protected. For example, given a hash table A, if thread 1 is writing to A, then thread 2 must be prevented from reading from or writing to A.' 

I have some confusion, and I am not entirely sure if I understand correctly.

**Comment by greg7mdp** [comment]
Yes, it sounds like you should definitely use `std::mutex` instead of `phmap::NullMutex` in your map declaration. I would think that you'd get seg faults though, surprising you don't.

**Comment by littledoglily** [comment]
> Yes, it sounds like you should definitely use `std::mutex` instead of `phmap::NullMutex` in your map declaration. I would think that you'd get seg faults though, surprising you don't.

Thanks for your response. 
Another question is: if I dump a phmap::parallel_flat_hash_map<uint64_t, std::array<float, N>>, can I load it with phmap::parallel_flat_hash_map<uint64_t, std::array<float, N>, hmap::priv::hash_default_hash<Key>, phmap::priv::hash_default_eq<uint64_t>,  phmap::priv::Allocator<phmap::priv::Pair<uint64_t, std::array<float, N>>>, 4， std::mutex std::mutex>? Or load operation and dump operation must be the same

**Comment by littledoglily** [comment]
> Yes, I think it should work fine, the mutex type does not have to match. Also, as an alternative if needed, you can `swap` two `parallel_flat_hash_map` whose mutex type differ.

Thanks for your help.
