### ISSUE TITLE
GTEST_FLAG_GET GTEST_FLAG build issue

### ISSUE THREAD

**Issue by LargePrime** [greg7mdp/parallel-hashmap#249]
Hi
https://github.com/mhx/dwarfs/issues/238

I guess this should have been directed to you?

**Comment by greg7mdp** [comment]
You probably shouldn't be building the `parallel-hashmap` tests. Not sure why that happens in your cmake system as the phmap `CMakeLists.txt` builds the tests only when `CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR`.
