### ISSUE TITLE
Question: Hashmap as template parameter to another class

### ISSUE THREAD

**Issue by lczech** [greg7mdp/parallel-hashmap#256]
I am trying to write a class template that accepts a Hashmap as a template parameter, but in a way where the key and value types do not have to be defined, and instead are set by the class:

```cpp
template<template<typename, typename, typename...> class Hashmap = std::unordered_map>
class MyClass {
public:
    using MapType = Hashmap<std::string, int>;
    MapType my_map;
};
```

in order to allow for easy usage (user does not have to provide `std::string` and `int`), and because the key/value types are meant to be internal to the class anyway.

In other words, I'd like the class to be usable like this:

```cpp
MyClass<std::unordered_map> obj1;
MyClass<phmap::parallel_flat_hash_map> obj2;
```

This however fails to compile for `parallel_flat_hash_map`, as it contains a template parameter `size_t N = 4`, and non-type parameters are not allowed in variadic template template parameters...

Is there a way to get this to work, or do I have to change the template arguments of `MyClass` and have the user specify 

```
MyClass<phmap::parallel_flat_hash_map<std::string, int>> obj3;
```

explicitly each time?

Thank you in advance!
Lucas

**Comment by greg7mdp** [comment]
The user of the class could do this for example:
```
template <typename K, typename V>
using parallel_flat_hash_map = phmap::parallel_flat_hash_map<K, V, phmap::priv::hash_default_hash<V>, phmap::priv::hash_default_eq<K>, phmap::priv::Allocator<phmap::priv::Pair<K, V>>, std::mutex>;
```

and then use `parallel_flat_hash_map ` as the template argument for `MyClass`

**Comment by lczech** [comment]
Thanks! It didn't work with exactly that, as the `N` template param seems to be needed, but as I am happy with the defaults for most template params anyway, I got it to work with this:

```cpp
template <typename K, typename V>
using parallel_flat_hash_map = phmap::parallel_flat_hash_map<K, V>;
```

and plug that one into `MyClass`.

Cheers and thanks again!
Lucas
