### ISSUE TITLE
Do you support c++11 stateful allocators?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [greg7mdp/parallel-hashmap#26]
Does parallel-hashmap ever make its own clean instance of my custom Allocator and allocates from that instead of a copy of the allocator I passed in the constructor?

**Comment by greg7mdp** [comment]
I don't think so.

**Comment by devshgraphicsprogramming** [comment]
That's good to hear, cause I have stateful STL-compatible allocators that can work with GPU memory ;)
