### ISSUE TITLE
Unsure how to use `if_contains`

### ISSUE THREAD

**Issue by kriscao-cohere** [greg7mdp/parallel-hashmap#264]
Hi, I'm trying to use the parallel_flat_hash_map implementation, and I want to test if a key exists in the hash map and if not, do some work and write the (key, value) entry into the hashmap. My code snippet looks something like this:

```
MyType value;
int key = 0;
if (!my_hash_map.if_contains(key, value) {
    value = do_some_work(key);
    my_hash_map[key] = value
}
```

However, my compiler complains with the following error:
```
cpp/../parallel-hashmap/parallel_hashmap/phmap.h:3326:58: error: static assertion failed
 3326 |         static_assert(std::is_invocable<F, value_type&>::value);
      |                                                          ^~~~~
cpp/../parallel-hashmap/parallel_hashmap/phmap.h:3332:27: error: no match for call to ‘(MyType) (std::pair<const int, MyType >&)’
 3332 |         std::forward<F>(f)(*ptr);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~
 ```
 
 What am I doing wrong? FWIW I don't get any error highlighting in my code and I believe it should be correct.

**Comment by kriscao-cohere** [comment]
Sorry, completely my issue (as expected), I didn't understand from the type hint of `if_contains` that the second argument should be a lambda that gets called with the map value type (i.e. `std::pair<K, V>`). I looked at the test cases and finally understood. Sorry for the noise!

**Comment by greg7mdp** [comment]
> Sorry, completely my issue (as expected), I didn't understand from the type hint of `if_contains` that the second argument should be a lambda that gets called with the map value type (i.e. `std::pair<K, V>`). I looked at the test cases and finally understood. Sorry for the noise!

No problem, the doc is not great, thanks for using phmap!
