### ISSUE TITLE
Implement SSE code for ARM processors for best performance (similar to GroupSse2Impl).

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [greg7mdp/parallel-hashmap#27]
I wonder what happens to your SSE code on ARM CPUs that only have NEON.

**Comment by greg7mdp** [comment]
If SSE is not available, the code defaults to a non-SSE, portable C++ implementation (see GroupPortableImpl)

**Comment by greg7mdp** [comment]
We could probably add ARM support by using https://github.com/jratcliff63367/sse2neon

**Comment by devshgraphicsprogramming** [comment]
ok, you might want to open an issue for this, my team could contribute at some point in 2020

**Comment by greg7mdp** [comment]
Sure, I have reopened the issue.

**Comment by greg7mdp** [comment]
see https://github.com/abseil/abseil-cpp/issues/1096
