### ISSUE TITLE
Document more clearly a simple example of how to use it safely in a multi-threaded scenario

### ISSUE THREAD

**Issue by abletaz** [greg7mdp/parallel-hashmap#28]
When using parallel-hashmap and telling it a mutex type to use internally for thread-safety .... you say it's not safe to use iterators while another thread may be writing .... 

Obviously _iterating_ with those iterators I would expect to not be thread-safe.

But presumably it _is_ thread-safe to, without any extra external locking, do a .find() - which returns precisely such an iterator - and then retrieve the value from that iterator ....?

Otherwise it's not at all clear how the class could be at all used thread-safely, e.g. how does simply one retrieve a value from the map (in such a case, generally using the [] operator is less desirable that using find(), as we don't want to potentially be writing a new entry to the map as a side-effect of our get, and creating extra contention in the process etc). 

Note - I did look at the examples and tests, but trying to wade through all the macros is a ton harder and less informative than if one could just read some simple example code along with an explanation of exactly what is and isn't safe to do.

**Comment by greg7mdp** [comment]
> But presumably it is thread-safe to, without any extra external locking, do a .find() - which returns precisely such an iterator - and then retrieve the value from that iterator ....?

Sorry, no, the internal synchronization allows only for concurrent write access. I have updated the readme to be more clear about this.
