### ISSUE TITLE
intel compiler warning

### ISSUE THREAD

**Issue by rzolau** [greg7mdp/parallel-hashmap#30]
Intel C++ compiler issues warning:

warning #2196: routine is both "inline" and "noinline"

for methods marked as PHMAP_ATTRIBUTE_NOINLINE. I think this is known issue with icpc, that could be explicitly addressed by adding intel specific pragma.

**Comment by greg7mdp** [comment]
Thanks for the report. I just checked in a new version of phmap_config.h. Does it solve the issue?

**Comment by rzolau** [comment]
Thanks for prompt response and great code. To my surprise, the issue is still there. However, let me investigate more to provide better feedback. FWIW I am working with icpc version 19.0.4.243 (gcc version 9.2.1 compatibility).

**Comment by greg7mdp** [comment]
I pushed in a different change. Can you try again? Thanks!

**Comment by rzolau** [comment]
Works :-)

**Comment by greg7mdp** [comment]
great, thanks @rzolau
