### ISSUE TITLE
Does not compile on MSVSC 2017 - Intrinsics Error

### ISSUE THREAD

**Issue by JeremyBYU** [greg7mdp/parallel-hashmap#32]
Compiler Error:

```
c:\users\jerem\documents\umich\research\iros\polylidarv2\polylidar\parallel_hashmap\phmap_bits.h(265): error C3861: '_BitScanForward64': identifier not found
c:\users\jerem\documents\umich\research\iros\polylidarv2\polylidar\parallel_hashmap\phmap_bits.h(298): error C3861: '_BitScanForward': identififier not found
```

These errors occured on Line 265 of `phmap_bits.h`. Googling the error informed me that we need to have a `#include <intrin.h>` before this line number. However this `#include` does not come until Line 327: https://github.com/greg7mdp/parallel-hashmap/blob/8834c9d62452a2d363695de7253c49cabff7ade9/parallel_hashmap/phmap_bits.h#L327

To fix this issue I **deleted** this include statement and put it below Line 162, here:
https://github.com/greg7mdp/parallel-hashmap/blob/8834c9d62452a2d363695de7253c49cabff7ade9/parallel_hashmap/phmap_bits.h#L162

After this change it worked just fine for me. I think the only issue is that there should be a guard to check for X64 architecture. I tried the `#include` other places but additional errors kept appearing. 

Hope this helps.

**Comment by greg7mdp** [comment]
Hi @JeremyBYU, thanks a lot for the report, I'm travelling this week but I should be able to look at the issue this week-end.  Wondering why you are having an issue with msvc2017 as it is tested in the [appveyor ci](https://ci.appveyor.com/project/greg7mdp/parallel-hashmap)?

**Comment by JeremyBYU** [comment]
I'm really not sure. The error reported seemed to make sense though. Maybe
something is different between compiler versions and build environments for
me.

**Comment by JeremyBYU** [comment]
I forgot to mention that I am building a python c++ extension using setuptools. It calls the msvsc compiler (cl.exe).

**Comment by greg7mdp** [comment]
Should be fixed with this [checkin](https://github.com/greg7mdp/parallel-hashmap/commit/6808256b6c8bbb6aeca9fd22cdb1b4750d710aaa)

**Comment by greg7mdp** [comment]
@JeremyBYU issue should be fixed, if not please reopen it. Thanks again for reporting it.
