### ISSUE TITLE
[Question] Can I assume time-complexity of O(1) for read / write?

### ISSUE THREAD

**Issue by wbrickner** [greg7mdp/parallel-hashmap#38]
Hello,

I couldn't find any info about the theoretical time complexity.

I'd like to check with an author that this package has an O(1) time complexity for accessing an element / inserting an element.

This is what most people assume when you use the word 'hashmap', but maybe it's not implemented this way, but as long as it remains approx. O(1) in small n, it's "O(1) enough" for me.

Thank you.

**Comment by greg7mdp** [comment]
@wbrickner yes you are correct inserting an element or lookup is done in constant time, or O(1), in the phmap containers. 
- For lookup this is always the case. 
- For insertion, this is the case as well, except for the rare case where the insertion causes the table to resize, in which case this insertion will be O(n).

**Comment by greg7mdp** [comment]
Closing the issue, but feel free to ask more questions of clarifications if needed. Thanks!

**Comment by wbrickner** [comment]
I use built-in hash functions on `unsigned long` keys, which are always monotonically ascending, and should have some gaps (or they can be all counting up with no gaps, neither can be assumed).  I've assumed the built-in hash function will perform well under these conditions. In your estimation is that correct?

**Also, what is the time complexity for `.clear()`? In `std::unordered_map`, it's O(n).
Is this still the case with the `phmap` containers, or has something clever been done?**

Is there any table which describes the time complexity of all the operations, because they're not necessarily the same as `std::unordered_map`, and I like to keep a note of time complexity of all methods on my classes, many of which now depend on the complexity of the `phmap` containers.

Thank you very much for your help!

**Comment by greg7mdp** [comment]
> I use built-in hash functions on unsigned long keys, which are always monotonically ascending, and should have some gaps (or they can be all counting up with no gaps, neither can be assumed). I've assumed the built-in hash function will perform well under these conditions. In your estimation is that correct?

yes, that is correct. Whether there are gaps or not should not make a difference.

> Also, what is the time complexity for .clear()? In std::unordered_map, it's O(n).
Is this still the case with the phmap containers, or has something clever been done?

Indeed something smart is being done if the capacity is > 127. In that case, the memory array is simply deallocated, so it will be O(1) for types with no destructors. Of course, if the types stored in the hash map have destructors, it will be O(n) since all destructors have to be executed.

> Is there any table which describes the time complexity of all the methods? I know they're not necessarily the same as std::unordered_map, and I like to keep a note of time complexity of all methods on my classes, many of which now depend on the complexity of the phmap containers.

I don't have such a table at this time. Is there one for `std::unordered_map`? Besides the `.clear()` optimization I mentioned, I don't think it would be different from `std::unordered_map`.

**Comment by wbrickner** [comment]
There's not a centralized table AFAIK, but all online documentation for the STL containers provide theoretical time complexity for all methods.

If I want to remove all keys, then repopulate the table with a nearly identical set of keys with all new values, is there a non-standard method which would be more efficient than the complete deallocate-reallocate pattern? Maybe it's not an issue, idk.

Also I'm no C++ expert, are memory deallocations generally O(1)? I assumed all large memory de/allocations would resemble O(n) behavior?

Thanks!

**Comment by greg7mdp** [comment]
> If I want to remove all keys, then repopulate the table with a nearly identical set of keys with all new values, is there a non-standard method which would be more efficient than the complete deallocate-reallocate pattern? Maybe it's not an issue, idk.

There is no non-standard method for this. I would do clear(), reserve(expected_size), and then insert new items. Should be very efficient, and it is hard to imagine some non--standard method which would be faster.

> Also I'm no C++ expert, are memory deallocations generally O(1)? 

yes, they are, unless you are deallocating an array of C++ objects which have destructors, But deallocating an array of basic types (int, long, etc...) or objects with empty destructors is O(1).

**Comment by greg7mdp** [comment]
I had a quick look at the complexities listed for `std::unordered_map` and I do believe that the one for phmap will be the same (modulo the `clear()` optimization I already mentioned).
