### ISSUE TITLE
Bug with allocator?

### ISSUE THREAD

**Issue by WieszKto** [greg7mdp/parallel-hashmap#39]
Hey. I try implement parallel hashmap to this solution [IrrlichtBaw](https://github.com/WieszKto/IrrlichtBAW)
I change 
> std::unordered_map

 to your 
> phmap::flat_hash_map

[Code where you can look at this](https://github.com/WieszKto/IrrlichtBAW/commit/8ed7cb1697e7dc7012840d9d87d7e92dc206373f#diff-e40201c73244abcec6c9b9ba7fcdc0a2R63)

 and i have error with allocator

> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2338	You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member "type" would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conforming behavior.	IrrlichtServer	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\type_traits	1061
> 

Its a bug ?

My [Output](https://gist.github.com/WieszKto/b745c8d81ea13f6618f38071aeb89ef7)

**Comment by greg7mdp** [comment]
Doesn't look like a bug. Can you try adding the compilation flag `-D_ENABLE_EXTENDED_ALIGNED_STORAGE`

**Comment by greg7mdp** [comment]
closing the issue... please reopen if necessary.
