### ISSUE TITLE
btree_set fails to insert what should be a unique object

### ISSUE THREAD

**Issue by timwoj** [greg7mdp/parallel-hashmap#41]
```
#include "parallel_hashmap/btree.h"

struct Test
	{
	int a;
	int b;
	};

class Comparer {
public:
	bool operator()(const Test& l, const Test& r) const noexcept
		{
		return l.a < r.a;
		}
	};

using HashSet = phmap::btree_set<Test, Comparer>;

int main(int argc, char** argv)
	{
	Test a { 1, 1 };
	Test b { 2, 1 };
	Test c { 2, 2 };

	HashSet h;
	auto it = h.insert(a);
	if ( ! it.second )
		printf("failed to insert a\n");

	auto it2 = h.insert(b);
	if ( ! it2.second )
		printf("failed to insert b\n");

	auto it3 = h.insert(c);
	if ( ! it3.second )
		printf("failed to insert c\n");
	}
```

I would expect that to insert all three elements, but for some reason `c` fails to insert what should be a unique object.

**Comment by greg7mdp** [comment]
@timwoj the comparer provided only compares a, so two objects that have the same value for a compare as equal.

**Comment by greg7mdp** [comment]
from https://en.cppreference.com/w/cpp/container/set:
> Everywhere the standard library uses the Compare requirements, uniqueness is determined by using the equivalence relation. In imprecise terms, two objects a and b are considered equivalent if neither compares less than the other: !comp(a, b) && !comp(b, a).
