### ISSUE TITLE
std::result_of is deprecated in C++17 and removed in C++20 causing compilation errors

### ISSUE THREAD

**Issue by Zoodinger** [greg7mdp/parallel-hashmap#54]
Trying this with MSVC with C++20 enabled and I get the following error by trying to use flat_hash_map:
`error C2039: 'result_of': is not a member of 'std'`

Looking it up it seems std::result_of was deprecated in 17 and removed in 20

**Comment by greg7mdp** [comment]
This should not happen with the current version of phmap on github, it was fixed a couple months ago.

**Comment by Zoodinger** [comment]
I'm using the latest parallel-map version (commit `d02fd308c4b0e4f9d5ef3843ff6e424d194b6c8e`) and compiler version `MSVC 19.26.28806.0`.

I can see there's a condition that checks for `__cplusplus` version in `phmap_base.h`  to determine whether to use result_of or invoke_result_t:
```#if __cplusplus >= 201703L```

The `__cplusplus` macro has the value `199711` for me.

**Comment by greg7mdp** [comment]
Please try the latest version. It should work even without the `/Zc:__cplusplus` flag. Thanks for reporting the issue!
