### ISSUE TITLE
How can I view the contents of a flat_hash_set or flat_hash_map?

### ISSUE THREAD

**Issue by sweinst** [greg7mdp/parallel-hashmap#55]
Hi,

How can I see the contents of a flat_hash_set?

If I knew how to do it, I could write a gdb pretty-printer for it.

At the moment, it's impossible to see the contents of the set, at least for me who doesn't know the structure

**Comment by greg7mdp** [comment]
OK, let me see what I can do.

**Comment by sweinst** [comment]
Thanks. I just need to know how to go from one (key, value) to another and detect the end of the sequence

**Comment by sweinst** [comment]
Hi, I've made a pull request which adds a python script for LLDB: phmap_lldb.py. Could you have a look?

**Comment by greg7mdp** [comment]
I didn't really try it, but I assume that the python script you provided does the job. Please reopen if it is not the case. Thanks!
