### ISSUE TITLE
hash function

### ISSUE THREAD

**Issue by taranbis** [greg7mdp/parallel-hashmap#56]
Hello, 

There are 2 ways to give an object a hash function.

However, I am working with memory addresses and I wish I could keep them the same. I tried, specializating the template<> Hash for size_t to return the identity (which I saw that it is already being done like in phmap_utils.h), however printing the hash value in the insert or find is totally different. That might be because of the control bits, if I am not mistaken.

Is there a way I could just pass the hash function as the identity function, so that when I try to store a memory address as the key, it will no longer be hashed ? 

All the best!

**Comment by greg7mdp** [comment]
Why does it matter to you? The hash value only controls where it is stored, not what is stored.  I'm not quite understanding why the hash value would matter?

**Comment by taranbis** [comment]
I was hoping I could skip computing it, since what I am using as key is already similar to a hash value

**Comment by greg7mdp** [comment]
No, sorry. A pointer is not a very good hash value anyways, the low-order bits are typically 0 because of alignment. Also it would not make a significant difference in speed I believe.
