### ISSUE TITLE
Is it feasible to make iterators bidirectional

### ISSUE THREAD

**Issue by rzolau** [greg7mdp/parallel-hashmap#58]
In some applications it would be desirable to have bi-directional iteration over the hash table (even though the standards specifies that iterators are only forward iterators). Would it be possible to add such functionality to node_ and flat_ hash tables?

**Comment by greg7mdp** [comment]
Yes, it should be possible. Out of curiosity, can you give me an example of what this would be useful for?

**Comment by rzolau** [comment]
Without going into details we have a set of tasks, described by somewhat heavy objects (potentially with heap allocation). Tasks are generated by a user code, and in some cases could be redundant (and that should be detected). Hence tasks are maintained in a hash table. Once tasks are generated, they are processed by a distributed system in which a remote host may steal a task from any other host. Since tasks are already in a hash table, we view that table as a list (we do not care about order in which tasks are processed, hence forward iteration is sufficient). However to minimize synchronization due to work stealing, stolen tasks are taken from the "end" of the list (with simple CAS to check in front of the list did not advance beyond the end of the list). In order to be able to iterate from the "end" of the list (i.e., table) bidirection is handy ;-)

Question, I am not entire sure of details of implementation of phmap (btw, great product) so what is the current cost of advancing an iterator?

**Comment by greg7mdp** [comment]
I understand, that makes sense. Let me looks at making the iterator bidirectional (BTW advancing the iterator is very fast). In the meanwhile maybe you could use phmap::btree which has bidirectional iterators.

**Comment by greg7mdp** [comment]
Hi @rzolau , I have added support for bidirectional iterators on non-parallel hash maps or sets. 
In order for this support to be enabled, please define the preprocessor macro `PHMAP_BIDIRECTIONAL=1`. Hope this works for you.
