### ISSUE TITLE
Python Bindings for Parallel Hashmap

### ISSUE THREAD

**Issue by atom-moyer** [greg7mdp/parallel-hashmap#6]
Hi all,

I have created a python package that binds parallel-hashmap with numpy integration. The package is not finished, but it has complete, vectorized POD object support such as ints, floats, and bools. There is limited support for strings. I plan to precompile some simple tuples and arrays in the future. Extending new datatypes should be fairly straight forward.

I was able to achieve approximately comparable performance to the c++ implementation without any optimization of the bindings yet. (~30 seconds and 2100MB memory for 100M 8B:8B insertions).

The link to the repo is here:  https://github.com/atom-moyer/sparsepy.git

Would we be interested in advertising that package on this page? 

This is my first open source contribution, so I am quite excited to help as many people as I can with their hash map needs.  My engineering research relies heavily on prototyping protocols which require high performance hash maps. Therefore, I have a personal interest in developing the fastest, smallest, and easiest hash maps possible.

**Comment by greg7mdp** [comment]
Hi Adam,

Your repository looks great! Certainly, I'll be happy to advertise this python binding here! I'm actually working on adding a few changes in the parallel hashmap that should be ready on monday. Why don't we wait a couple day till I release version 1.2, and then when you tell me that you are in a stable state in your repository I'll add the link in my README.md.

**Comment by atom-moyer** [comment]
Awesome! That makes sense to me.

**Comment by greg7mdp** [comment]
Hi @atom-moyer , I just released version 1.2. Please let me know when you feel that your binding is ready.
Thanks - greg

**Comment by atom-moyer** [comment]
Hey Greg,

I think my package is ready to share! I have renamed the repo since my last comment.

https://github.com/atom-moyer/getpy.git

As of now I fully support all simple datatypes that pybind11 can natively support in numpy arrays (ints, uints, char arrays, floats, and bools).

Later I plan to support more complicated datatypes such as the combinations standard types in pairs and tuples.

Also, I hope to take advantage of your parallel performance and break the python GIL within the vectorized methods in the future.

**Comment by greg7mdp** [comment]
Looks great! Just added the link at the end of the README with the "about" from your page.
