### ISSUE TITLE
Ability to manipulate a hash_map value behind the write lock

### ISSUE THREAD

**Issue by bpmckinnon** [greg7mdp/parallel-hashmap#60]
I've encounter a case where I would like to modify the value inside the hash map in a thread-safe way.  I would like to propose a function similar to **if_contains** that I have so far named **if_modify**.  The difference between the two functions is if_modify is not const, and it locks the unique_lock rather than the shared_lock.  Otherwise they use the same function body.

**Comment by greg7mdp** [comment]
Would you be OK with keeping the `if_contains` name but making a non-const version?

**Comment by bpmckinnon** [comment]
I had considered that, but my concern I thought, should the const state of the current hash map affect which lock is selected?  I think not, since it feels unexpected, which is why I've added a second function.

**Comment by greg7mdp** [comment]
OK, makes sense, I just changed the name of the mutable `if_contains` to `modify_if`. The `if_modify` sounded wrong to me.

**Comment by bpmckinnon** [comment]
Yeah I was never happy with if_modify.  modify_if sounds good to me!

**Comment by JonathanFry3** [comment]
Similarly, I need the functionality of __operator[]__ with the follow-up code behind your lock.

I have an app that collects a large map whose mapped values are minimum values of  positive integers.  Single-threaded, the code looks like:

    value_type & val = map[key];
    if (val == 0 || x < val) val = x;

I could use your __modify_if()__, but a second search would be required if the key was not already in the map, and two threads could race inserting it.

I don't know what to call it. __find_or_insert()__?

**Comment by bpmckinnon** [comment]
I had thought of a similar situation, but the only way I could think for it to work was to pass a lambda (or value) to emplace and a lambda to modify which seems a bit heavy.  Would something like emplace_or_modify(key, emplace, modify) make sense?

**Comment by JonathanFry3** [comment]
Seems a bit heavy to me, too.  For __operator[]__, the standard says the default constructor will be used if an entry is created.  That seems sufficient.

**Comment by bpmckinnon** [comment]
What if the modify_if function was insert_or_modify instead, since the modify_if name always felt a bit yuck.  And the insert_or_modify function takes a lambda that receives a bool that is true if the element was newly inserted, and false if it already existed, and a reference to the value.  It could be default constructed, but with the bool flag it would allow for the case where your min value is 0.

**Comment by greg7mdp** [comment]
I just added the new API `try_emplace_l`. It is just like `try_emplace`, but it takes a function as a second parameter which allows to modify the value if it was already present. 

@JonathanFry3, I think it should fulfill your need, as you could change:
```
mapped_type & val = map[key];
if (val == 0 || x < val) val = x;
```
to
```
map.try_emplace_l(key, [x](mapped_type &v) { if (val == 0 || x < val) val = x;});
```

**Comment by greg7mdp** [comment]
Yes, I have updated `try_emplace_l` so that the lambda is called only when the key was already present.

**Comment by JonathanFry3** [comment]
For my purposes, I need the lambda called whether or not the key was already present.

**Comment by greg7mdp** [comment]
@JonathanFry3 , can you explain why please?

**Comment by bpmckinnon** [comment]
I think the main idea is to get as much work as possible done on a single lock.  So the lambda is always called, but in the case where it's not present it's default constructed and immediately passed to the lambda.

**Comment by greg7mdp** [comment]
You can pass arguments to construct the value as you wish (under the lock) if the key is not already present, so I don't see the need for the lambda in this case.

**Comment by JonathanFry3** [comment]
__try_emplace_l__ looks like it will do what I need.  My code will look like

    try_emplace_l(key, x, [x](mapped_type&v){if (x < v) v = x;});

Thanks.

**Comment by greg7mdp** [comment]
yes, except you should swap the last two arguments (lambda comes first).

**Comment by greg7mdp** [comment]
@bpmckinnon just to let you know I'm changing slightly the extended APIs so that the lambda is called with the value_type and not the mapped_type. This is so these APIs are usable with the sets, not only the maps. Thanks!

**Comment by bpmckinnon** [comment]
Sounds good thanks for the heads up
