### ISSUE TITLE
Add Folly ConcurrentHashMap to Benchmarks

### ISSUE THREAD

**Issue by benstadin** [greg7mdp/parallel-hashmap#62]
Very interesting library! I wonder how the parallel map compares to Folly's ConcurrentHashMap [1]. I think this is a closer comparison than F14 Map.

[1] https://github.com/facebook/folly/blob/master/folly/concurrency/ConcurrentHashMap.h

**Comment by greg7mdp** [comment]
Not quite sure what to do on this - so closing the issue.
