### ISSUE TITLE
Question about the capacity upper bound

### ISSUE THREAD

**Issue by gtarcoder** [greg7mdp/parallel-hashmap#66]
Hi @greg7mdp I find the following documentation of this repo.
`
The hashmaps and btree provided here are built upon those open sourced by Google in the Abseil library. The hashmaps use closed hashing, where values are stored directly into a memory array, avoiding memory indirections. By using parallel SSE2 instructions, these hashmaps are able to look up items by checking 16 slots in parallel, allowing the implementation to remain fast even when the table is filled up to 87.5% capacity.
`
But I have no idea why we get capacity upper bound at **87.5%** when we use SSE2 which enables cpu to fetch 16 slots at the same time, Could you help to explain it ?

**Comment by greg7mdp** [comment]
Well, the fuller the hash map, the higher the probability of collision when inserting new values. 87% was found to be a good threshold for resizing the hash map to maintain good performance while minimizing memory usage.

**Comment by gtarcoder** [comment]
> Well, the fuller the hash map, the higher the probability of collision when inserting new values. 87% was found to be a good threshold for resizing the hash map to maintain good performance while minimizing memory usage.

ok, so the 87.5% is a empirical value or a measured value, not a value calculated by math formula, such as 7/8, right? If so, I am wondering why the threshold is 87.5% :)

**Comment by greg7mdp** [comment]
I don't know the specific reason this value was arrived at, but yes I suppose it is 7/8th.
