### ISSUE TITLE
PHMAP_HAVE_SSSE3 is not set to 1 in Windows.

### ISSUE THREAD

**Issue by aractnido** [greg7mdp/parallel-hashmap#67]
phmap_config.h
Visual C++ does not define ```__SSSE3__``` and therefore ```PHMAP_HAVE_SSSE3``` ends up being 0 all the time.

It would be good to enable this flag if we compile with either /arch:AVX2 or /arch:AVX512 in Visual C++.

**Comment by greg7mdp** [comment]
Does this change work for you?
