### ISSUE TITLE
prefetch_hash is noop for Windows.

### ISSUE THREAD

**Issue by aractnido** [greg7mdp/parallel-hashmap#68]
Hardware prefetching is hard. Prefetching to early is bad, prefetching too late is bad.
Hardware prefetching is OS independent, so if phmap knows that it yields good numbers to prefetch in Linux, it should be the same for Windows.

We could do for Windows:
```
        auto seq = probe(hash);
        _mm_prefetch(static_cast<const void*>(ctrl_ + seq.offset()), _MM_HINT_NTA);
        _mm_prefetch(static_cast<const void*>(slots_ + seq.offset()), _MM_HINT_NTA);
```

**Comment by greg7mdp** [comment]
Thanks a lot for the suggestion. Does this work for you? Thanks - greg
