### ISSUE TITLE
Hash function accessibility

### ISSUE THREAD

**Issue by Andersama** [greg7mdp/parallel-hashmap#71]
It looks as though find() has two public forms to use, one with and without a hash. Trying to reach the hash function or recreate it is a hassle. Presumably:
```c
    template <class K>
    size_t hash(const K& key) {
        return HashElement{hash_ref()}(key);
    }
```
Should be static / public? Such that it'd be possible to perform lookups with a hash across multiple data structures.
```c
phmap::flat_hash_set<std::string_view> some_set_of_strings;
phmap::flat_hash_set<std::string_view> some_other_set_of_strings;
...
std::string_view some_string = "some string"sv;
auto some_hash = phmap::flat_hash_set<std::string_view>::hash(some_string);
if (some_set_of_strings.contains(some_string, some_hash)){
...
} else if (some_other_set_of_strings.contains(some_string, some_hash)){
...
}
```
Would also lead me to think there should be a contains() variation w/ the hash like find(). Eg:
```c
    template <class K = key_type>
    const_iterator find(const key_arg<K>& key, size_t hash) const {
        return const_cast<raw_hash_set*>(this)->find(key, hash);
    }
    template <class K = key_type>
    const_iterator find(const key_arg<K>& key) const {
        return find(key, HashElement{hash_ref()}(key));
    }

    template <class K = key_type>
    bool contains(const key_arg<K>& key) const {
        return find(key) != end();
    }
//to match find()'s interface
    template <class K = key_type>
    bool contains(const key_arg<K>& key, size_t hash) const {
        return find(key, hash) != end();
    }
```

Unless I'm misunderstanding the hasher function and it's dependent on the set or map in some way.

**Comment by greg7mdp** [comment]
Yes, @Andersama, I agree, just added these. They are not static, but member functions, in case that creating a hash function from the template type is expensive (which is probably unlikely, but still). Be aware that sharing the hash value between different hash tables will work only if they have the same HASH template parameter.

**Comment by greg7mdp** [comment]
Closing the issue, but let me know if you need something else.

**Comment by Andersama** [comment]
Nope, just was wondering since it seemed the api was leaning towards having the hash function available for use it was just odd that it wasn't forward facing. I've made my own edits locally, I added:
```c
    template <class K = key_type>
    size_t hash(const key_arg<K>& key) {
        return HashElement{ hash_ref() }(key);
    }
```
To the public sections and fowarded that because I was just following along. Is key_arg significant?
