### ISSUE TITLE
any doc about the template parameters of the parallel_hash_map?

### ISSUE THREAD

**Issue by RiccardoRossi** [greg7mdp/parallel-hashmap#75]
Dear Developers,
     i was looking into this library, which  looks VERY promising. Unfortunately i am a bit lost at the moment of understanding the template parameters to be used.
Is there any place were i can find some minimal documentation?

specifically i wanted to have 

~~~
key = std::size_t
value = std::size_t
mtx = std::mutex
~~~

how would the constructor of the hash map look like in this case?
(i tried to look into bench.cpp, but admittedly i got lost with the macro definitions)

**Comment by greg7mdp** [comment]
Hi @RiccardoRossi, 

Thank you for the interest! Indeed this could use more documentation.

you can use:

```
    using Map = phmap::parallel_flat_hash_map<std::size_t, std::size_t,
                                              phmap::priv::hash_default_hash<size_t>,
                                              phmap::priv::hash_default_eq<size_t>, 
                                              std::allocator<std::pair<const size_t, size_t>>, 
                                              4, 
                                              std::mutex>;
```

Please be aware that the iterators returned (by `find` for example) cannot be safely read in a multithreaded environment.  Instead use `if_contains()`, which passes a reference value to the callback while holding the *submap* lock. Similarly, write access can be done safely using `modify_if`, `try_emplace_l` or `lazy_emplace_l`.

**Comment by greg7mdp** [comment]
Please note that the constant 4 creates 16 internal subtables. You can increase the parallelism and reduce lock contention by using larger constants, for example 5 would create 32 submaps, 6 -> 64, 8 -> 256, etc...

**Comment by RiccardoRossi** [comment]
Thx for the help. It looks like it works, also when calling it from an openmp loop

i attach here my simple test

~~~cpp
//compile with g++ -fopenmp -std=c++17 -O3 main.cpp
#include <vector>
#include <iostream>
#include <chrono>
#include <mutex>
#include "parallel-hashmap/parallel_hashmap/phmap.h"
#include "omp.h"
#include <execution>

int main() {
    
    std::cout << " n threads = " << omp_get_max_threads() << std::endl;    

    using Map = phmap::parallel_flat_hash_map<std::size_t, std::size_t,
                                              std::hash<size_t>,
                                              std::equal_to<size_t>, 
                                              std::allocator<std::pair<const size_t, size_t>>, 
                                              4, 
                                              std::mutex>;
    std::size_t total_items = 1e6;
    std::size_t nitems = total_items/omp_get_max_threads(); //items per thread
    Map q;
    

    std::size_t expected_sum = 0;
    auto start = std::chrono::system_clock::now();
    #pragma omp parallel
    {
        std::size_t ithread=omp_get_thread_num();
        std::size_t base =  ithread*nitems;

        #pragma omp atomic
        expected_sum += ithread*nitems;

        for(std::size_t i=0; i<nitems; ++i)
            q.try_emplace_l(base+i,
                    [&ithread](std::size_t& v) { v = ithread; }, // called only when key was already present
                    ithread);                    // argument to construct new value is key not present
    }
    auto stop = std::chrono::system_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "map insertion time = " << elapsed << std::endl;

    std::cout << "size = " << q.size() << std::endl;
    assert(q.size()==total_items);

    const auto& const_q = q;

    std::size_t sum=0;
    for(const auto& item : const_q)
        sum += item.second;

    assert(sum == expected_sum);

    start = std::chrono::system_clock::now();
    std::atomic<std::size_t> parallel_sum=0;
    std::for_each(
        std::execution::par_unseq,
        const_q.begin(),
        const_q.end(),
        [&parallel_sum](const auto& item)
        {
            parallel_sum += item.second;
        }
    );
    stop = std::chrono::system_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "parallel sum time = " << elapsed << std::endl;

    assert(sum == parallel_sum);

    return 0;
}
~~~

**Comment by greg7mdp** [comment]
Great! However you don't need to use `try_emplace_l` for the insertion since you never insert the same key twice, I think you can just do: `q.emplace(base+i, ithread);`.

Also you could try using 5 or 6 for the second to last template parameter to see if it is a little bit faster.

**Comment by RiccardoRossi** [comment]
dear @greg7mdp even though in this specific test i don't have repeated entries, it may well happen in my real testcase.
BTW, we are considering including your library in our project (called KratosMultiphysics) but we are a little afraid of the mix between openmp and c++11

on a side note, what does the last parameter of try_emplace_l mean?

**Comment by greg7mdp** [comment]
Dear @RiccardoRossi,

First, I wouldn't worry too much about mixing c++11 and openmp, unless maybe if you are using a very old compiler, because both have been out for a long time by now.

About `try_emplace_l`, normally [try_emplace](https://en.cppreference.com/w/cpp/container/map/try_emplace) takes a key, and then a list of arguments to construct a value. `try_emplace_l` is the same, except with an additional second argument (the lambda) which can be used to modify the value (under protection of the lock of the map) if it was already present.

**Comment by RiccardoRossi** [comment]
dear @greg7mdp i refer to the paramter that goes after the lambda, the one you suggested me to set to 2 ... or to 4,5

~~~cpp
q.try_emplace_l(base+i,
                    [&ithread](std::size_t& v) { v = ithread; }, // called only when key was already present
                    2); --> what does this two mean?
~~~

about OpenMP the problem is that c++11 and OpenMP are not _guaranteed_ to be compatible. We will need to check with quite a few compilers

**Comment by greg7mdp** [comment]
If the key is not present, it would do the same thing as:

```
q.try_emplace(base+i, 2); 
```

or `q[base+i] = 2;`

except that the last version is not thread-safe.
