### ISSUE TITLE
for the same key, hash(key) is computed differently in different file

### ISSUE THREAD

**Issue by Sweetjy** [greg7mdp/parallel-hashmap#78]
I build a `extern phmap:: flat_hash_map<const char*, unsigned short> mp1;`  in A.h
everything is okey if I insert and find the key in the same .cc,  but when I find the key in another .cc, the hash(key) is computed differently, so I can't find the value.

my program like this
B.cc 
`mp1.insert(std::pair<const char*, unsigned short>("key0",10));  bool find = mp1.contains("key0")   // find = true and mp1["key0"] = 10`
C.cc
`bool find = mp1.contains("key0");    //find = false!! and mp1["key0"] = 0`
`for(auto &n: mp1){ bool find = mp1.contains(n.first);}    //find = true and mp1["key0"] = 10`
do u know why is it so??

**Comment by greg7mdp** [comment]
It looks like you are storing pointers in your map, not strings. You can have two different pointers to the same string.
Probably what you want to use is: `phmap:: flat_hash_map<std::string, unsigned short> mp1;`
