### ISSUE TITLE
try_emplace_l does not function as documented

### ISSUE THREAD

**Issue by NavidMitchell** [greg7mdp/parallel-hashmap#79]
Hello the phmap::parallel_flat_hash_map.try_emplace_l function does not seem to work as documented. 

The docs say 

`    // if map does not contains key, it is inserted and the mapped value is value-constructed 
    // with the provided arguments (if any), as with try_emplace. 
    // Then the lambda is called with the mapped value (under write lock protection) and can 
    // update the mapped value.
    // ---------------------------------------------------------------------------------------`

But it appears the lambda is only called if the value already exists in the map.

**Comment by greg7mdp** [comment]
Thanks @NavidMitchell you are right the comment was misleading. I have updated it. I appreciate the feedback!

**Comment by NavidMitchell** [comment]
Thank you for the prompt reply. It would be nice for my use case to have a function that behaved as explained in the original comment. For modifying existing values I can use the modify_if. But I need a function that locks the key while adding a new key. Something similar to computIfAbsent from java. Would you consider a pull with this functionality? 

Thank you,
Navid

**Comment by greg7mdp** [comment]
Hi @NavidMitchell, the check for the key's presence, and its addition if not already present, is currently done while the hash map is locked. Is that not enough for your purpose?

**Comment by NavidMitchell** [comment]
Hi @greg7mdp, I need to be able to run a lambda after creating the new value while the key remains locked. This way I can call custom initialization logic on the value. I guess I could create a facade that called the initialization logic in the constructor of the value.. I think the behavior of the method had me confused since I am using modify_if for the case where the value exists. But the try_emplace_l calls behaves the same as modify_if when there is a value but differently when no value exists.  In java's ConcurrentHashmap there are computeIfAbsent and computeIfPresent methods that allow concurrent modification of a value by locking the key and calling a lambda if the value is absent or present accordingly. It seems to me this behavior is a little more succinct.

**Comment by greg7mdp** [comment]
Hi @NavidMitchell why don't you add your custom  initialization logic in a constructor for the value, and then pass the parameters to invoke this constructor?

**Comment by NavidMitchell** [comment]
Hi, @greg7mdp that's what I will do thank you!

**Comment by greg7mdp** [comment]
Sure, thanks for using phmap!
