### ISSUE TITLE
absl::EqualTo does not exist

### ISSUE THREAD

**Issue by refi64** [greg7mdp/parallel-hashmap#8]
Not sure if it existed back when this was first added, but currently there is no absl::EqualTo, so compilation breaks when PHMAP_USE_ABSL_HASHEQ is defined. Workaround is to add this before including `phmap.h`:

```c++
namespace absl {
  template <typename T>
  struct EqualTo {
    bool operator()(const T& a, const T& b) const {
      return a == b;
    }
  };
}
```

At a glance, couldn't phmap just always use its own EqualTo? At least for me, I'm solely using PHMAP_USE_ABSL_HASHEQ for the hashing.

**Comment by greg7mdp** [comment]
Hi @refi64 , many thanks for reporting this issue, I will fix it later today.

**Comment by greg7mdp** [comment]
Hi @refi64, I have added another define for your use case: PHMAP_USE_ABSL_HASH

**Comment by refi64** [comment]
Thanks! I still have to ask though, what about the missing absl::EqualTo?

**Comment by greg7mdp** [comment]
The idea is that if you want to use Abseil functionality, then you need to include the Abseil header. This is probably what you are doing for `absl::Hash`, right?

**Comment by refi64** [comment]
@greg7mdp I mean that, based on both a local and [online code search](https://github.com/abseil/abseil-cpp/search?q=EqualTo&unscoped_q=EqualTo), there is not `absl::EqualTo` *anywhere*. The only thing is [absl::algorithm_internal::EqualTo](https://github.com/abseil/abseil-cpp/blob/38b704384cd2f17590b3922b97744be0b43622c9/absl/algorithm/algorithm.h#L33), which is presumably for internal use only and also takes the template arguments on `operator()` instead of the class itself.

**Comment by greg7mdp** [comment]
My bad, sorry, I completely misunderstood what you meant. Just checked in the fix.
