### ISSUE TITLE
Don't use transparent images

### ISSUE THREAD

**Issue by MarekKnapek** [greg7mdp/parallel-hashmap#80]
Hi, thanks for the library looks very nice, I consider it using in my projects.

I noticed that you, and many more people on the Internet, are using transparent images (GIF in this case). This is bad, because the transparency looks different on each computer. It might look nice on your PC, but is unreadable on my PC. The background color in each viewing program (image viewer, web browser) is different. In some it is white, in some it is black and in others it is checkerboard pattern.

In attachment you can see how does your documentation look like on my Android phone with black color scheme in Chrome web browser with GitHub also in black color scheme versus in incognito mode.

Best Regards,
Marek.

![DocWhite](https://user-images.githubusercontent.com/13893067/104256074-bd15d500-547a-11eb-94cc-5f7de966fe30.jpg)
![DocBlack](https://user-images.githubusercontent.com/13893067/104256075-bdae6b80-547a-11eb-86a9-6ec4a35a59e2.jpg)

**Comment by greg7mdp** [comment]
Hi @MarekKnapek , thanks for the feedback, but I think what you are describing is due to the way github renders the MarkDown format, more precisely the tables in README.md. Because the table lines have an alternate background on successive lines, the only way for images to appear correctly is for them to have a transparent background. I'm not quite sure how I could improve this.

**Comment by MarekKnapek** [comment]
Hi @greg7mdp, I think we misunderstood each other. Yes, you are correct that you have no control how GitHub renders MarkDown. Yes, in white scheme it uses alternating white and gray table background and in black scheme it uses black background.

But no, transparency is not the way to render those equations. It is impossible to read black text on black background.

You can easily change all those .gif files to have white background (instead of transparent). They will appear a little weird on GitHub with black color scheme, but at least they will be readable. They will appear similar to your logo, which does use white (not transparent) background.

Marek

**Comment by greg7mdp** [comment]
I had a white background originally, but it looked really bad on the alternating white/gray table background. This is why I made the gif background transparent.
I do understand the issue, but I would prefer to find a solution which doesn't make it look bad on desktop.

**Comment by MarekKnapek** [comment]
You can watch discussion about this problem over here: https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/30 hope it helps.
