### ISSUE TITLE
Accessing internal sub hash maps

### ISSUE THREAD

**Issue by taranbis** [greg7mdp/parallel-hashmap#81]
Hi, 

In one project that I am working on, DRace (a data race detection tool), we are using this version of hash map as it is really fast especially for a high number of elements, as it is used, among other things, to map memory addresses to state classes. However, for long running programs, we need a way to remove data and a pretty cool feature that we tried is to remove an entire sub hash map of memory addresses and this worked quite well. However, your project is added as a submodule to our project and we don't want to keep a dangling fork. 

We use the following function for clearing a sub hash map:
```cpp
void dropSubMap(std::size_t index) {
    Inner& inner = sets_[index];
    auto& set = inner.set_;
    typename Lockable::UniqueLock m(inner);
    set.clear();
}
```
The previous code snippet is added in `phmap.h`, as ` std::array<Inner, num_tables> sets_; ` is declared private.

Is there a way to add a feature to remove an entire sub hash map of data (such as the function above) or at to make the array of sets accessible from outside or protected so that the class can be inherited and be able to access the sub hash maps?

Thanks in advance.

**Comment by greg7mdp** [comment]
Sure, and thanks for using phmap! I added the api (changed the name to clearSubmap) and also made the sets_ array protected.

**Comment by taranbis** [comment]
Hi, 

thanks a lot.

All the best!
