### ISSUE TITLE
Multithreaded insert example without re-calculating hash?

### ISSUE THREAD

**Issue by traversc** [greg7mdp/parallel-hashmap#82]
In the example you have:

```
1            size_t hashval = hash.hash(key);                // compute its hash
2            size_t idx  = hash.subidx(hashval);             // compute the submap index for this hash
3            if (idx / modulo == thread_idx)                 // if the submap is suitable for this thread
4            {
5                hash.insert(typename HT::value_type(key, 0)); // insert the value
6                ++(num_keys[thread_idx]);                     // increment count of inserted values
7            }
```
            
However, this calculates the hash twice. Once on line 1 and then on line 5 when you insert. 

Is there a way to do this lock-free without re-calculating the hash? If your key is a large struct, calculating the hash twice could be expensive.

**Comment by greg7mdp** [comment]
Hi @traversc ,

`find()` and `contains()` do have an overload that take a hash value, but insert doesn't. If I remember correctly the main reason was that `insert()` is already quite overloaded.

But you are right that it would be nice to have this for doing lock-free. Let me look into adding it. Maybe as extended APIs `insert_hv` and `emplace_hv`.

Thanks for the suggestion!

**Comment by greg7mdp** [comment]
Hi @traversc , sorry for the wait, I have added the `*emplace_with_hash(hashval, ...)` APIs

**Comment by greg7mdp** [comment]
Closing the issue, feel free to let me know if you have any issue using them. I tried them in the `bench.cc` you mentioned above with:
`hash.emplace_with_hash(hashval, key, 0); `
and it seemed to work fine.
