### ISSUE TITLE
phmap::parallel_flat_hash_map iterator times is much more than size

### ISSUE THREAD

**Issue by eyun221** [greg7mdp/parallel-hashmap#83]
I have just used parallel_flat_hash_map in my project like the following code, but why times > mp.size() ?

phmap::parallel_flat_hash_map<int,int> mp;
mp.emplace(xx,xx);
...

int times=0;
for(auto& p : mp){
    times++;
}

// times > mp.size()

**Comment by greg7mdp** [comment]
Hi @eyun221 

Here is a working program:

```
#include <iostream>
#include <parallel_hashmap/phmap.h>

int main()
{

    phmap::parallel_flat_hash_map<int,int> mp;
    mp.emplace(1,1);

    int times=0;
    for(auto& p : mp) {
        times++;
    }
 
    std::cout << "times: " << times << ", size:" << mp.size() << "\n";
    return 0;
}
```

and when I run it is Visual Studio 2019 the output is:

![image](https://user-images.githubusercontent.com/1496907/109422426-7556f880-79a9-11eb-89ac-ca9857709e0b.png)

Please provide a working program reproducing the issue and the information about the compiler used.

Thanks!

**Comment by eyun221** [comment]
i have got times > size in multi-thread code.

**Comment by eyun221** [comment]
can you review the iterator code to see there is some bug?

**Comment by greg7mdp** [comment]
Have you tries using a different map (like std::unordered_map) to see if the issue is still there.
