### ISSUE TITLE
erase_if

### ISSUE THREAD

**Issue by baklazan** [greg7mdp/parallel-hashmap#84]
Hello,

I'm trying to do the following operation in a thread-safe manner: if there is a value stored at `key` and it has some property `P()`, erase it. Is it possible? I'm using `parallel_flat_hash_map` with `std::mutex`.

So far, I came up with two bad "solutions":
```C++
bool shouldErase = false;
myMap.if_contains(key, [&shouldErase](V value){
  shouldErase = P(value);
}
if (shouldErase)
{
  myMap.erase(key); // not safe, another thread might have modified myMap[key] in the meantime
}
```
and
```C++
myMap.if_contains(key, [](V value){
  if (P(value)) {
    myMap.erase(key); // deadlock
  }
});
```

If there is no solution within the current API, I suggest extending it by something like this:

```C++
// if map contains key, lambda is called with the mapped value  (under write lock protection).
// If the lambda returns true, the key is subsequently erased from the map (the writer lock
// is only released after erase).
// ----------------------------------------------------------------------------------------------------
template <class K = key_type, class F>
bool erase_if(const key_arg<K>& key, F&& f)
```

**Comment by greg7mdp** [comment]
Solution #2 should work is you use `std::recursive_mutex` instead of `std::mutex`. But I like your `erase_if` idea as well.

**Comment by greg7mdp** [comment]
@baklazan just added `erase_if`. Thanks for the suggestion!
