### ISSUE TITLE
Equations in Readme are unreadable in Github's dark mode

### ISSUE THREAD

**Issue by kkiningh** [greg7mdp/parallel-hashmap#85]
Github's dark mode (under https://github.com/settings/appearance)  make it very difficult to read the equations in the Readme. Here's what I see in Google Chrome: 

![Screen Shot 2021-03-17 at 4 52 33 PM](https://user-images.githubusercontent.com/360345/111553399-8a6dae80-8741-11eb-9824-5719a961d361.png)

**Comment by greg7mdp** [comment]
I thing this is similar to issue #80, but unfortunately I don't have a good solution for this. I'm open to a solution that would look good in all modes if someone has a suggestion.

**Comment by kkiningh** [comment]
IMO, it would look better to just have a white background rather than be completely unreadable. If you don't like how it looks in the alternating background of the table, maybe you could try adding rounded corners plus a single pixel grey border around the image? That would make it look a little less obviously out of place.

![equations](https://user-images.githubusercontent.com/360345/111563418-29e86c80-8755-11eb-83c4-1d2fbf362ba7.png)

Another option might be to just use plaintext instead of equations. 

I agree there may not be a good solution currently though.

**Comment by kkiningh** [comment]
Example with more aggressive rounding + Github's dark dimmed theme.

![github_equations](https://user-images.githubusercontent.com/360345/111564402-e7c02a80-8756-11eb-90f6-38a1b994e249.png)

**Comment by greg7mdp** [comment]
This looks great! Do you want to provide a PR with the updated bitmaps? I would really appreciate it :-)

**Comment by kkiningh** [comment]
Sure - is there somewhere with the latex written out so I can copy and paste? Do you like the second or first one better?

**Comment by greg7mdp** [comment]
Oh, I don't believe I used latex (directly), if I remember correctly I think I used an online equation editor. 
I was thinking of starting with the existing images (which have a transparent background), and using photoshop fill the transparent background with white within a round rectangle mask or something. You think you might be able to ddo something like that?

**Comment by greg7mdp** [comment]
I do like the more aggressive rounding more.

**Comment by kkiningh** [comment]
I just typed it out myself. There was a parenthesization error in the first one and I removed the italics for the equations. Below is the latex I used for future reference.

```latex
O\left(\frac{\mathrm{size}()}{\mathrm{load\_factor}()} * (\mathrm{sizeof}(C :: \mathrm{value\_type}) + 1)\right)
O\left(\frac{\mathrm{size}() * 9}{\mathrm{load\_factor}()} + \mathrm{size}() * \mathrm{sizeof}(C :: \mathrm{value\_type})\right)
O\left(\frac{\mathrm{size}()}{0.4375} * (\mathrm{sizeof}(C :: \mathrm{value\_type}) + 1) * 0.5\right)
O\left(\frac{\mathrm{size}() * 9}{0.4375} * 0.5\right)
O\left(\frac{\mathrm{size}()}{0.4375} * (\mathrm{sizeof}(C :: \mathrm{value\_type}) + 1) * 0.03\right)
O\left(\frac{\mathrm{size}() * 9}{0.4375} * 0.03\right)
```

**Comment by greg7mdp** [comment]
Thanks again!
