### ISSUE TITLE
compiler errors with msvc

### ISSUE THREAD

**Issue by fabioparodi** [greg7mdp/parallel-hashmap#89]
using Microsoft Visual Studio Community 2019
Version 16.9.4

```
	phmap::btree_set<std::string> s;
	s.insert("");
```

makes linker errors:

2>test_generators.cpp
2>test_generators.obj : error LNK2005: "public: static class phmap::weak_equality const phmap::weak_equality::equivalent" (?equivalent@weak_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::weak_equality const phmap::weak_equality::nonequivalent" (?nonequivalent@weak_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_equality const phmap::strong_equality::equal" (?equal@strong_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_equality const phmap::strong_equality::nonequal" (?nonequal@strong_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_equality const phmap::strong_equality::equivalent" (?equivalent@strong_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_equality const phmap::strong_equality::nonequivalent" (?nonequivalent@strong_equality@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::partial_ordering const phmap::partial_ordering::less" (?less@partial_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::partial_ordering const phmap::partial_ordering::equivalent" (?equivalent@partial_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::partial_ordering const phmap::partial_ordering::greater" (?greater@partial_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::partial_ordering const phmap::partial_ordering::unordered" (?unordered@partial_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::weak_ordering const phmap::weak_ordering::less" (?less@weak_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::weak_ordering const phmap::weak_ordering::equivalent" (?equivalent@weak_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::weak_ordering const phmap::weak_ordering::greater" (?greater@weak_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_ordering const phmap::strong_ordering::less" (?less@strong_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_ordering const phmap::strong_ordering::equal" (?equal@strong_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_ordering const phmap::strong_ordering::equivalent" (?equivalent@strong_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>test_generators.obj : error LNK2005: "public: static class phmap::strong_ordering const phmap::strong_ordering::greater" (?greater@strong_ordering@phmap@@2V12@B) already defined in configmeasurapage.obj
2>   Creating library C:\Users\FabioParodi\Documents\RDI_WATCHER\unit_test\Debug\unit_test.lib and object C:\Users\FabioParodi\Documents\RDI_WATCHER\unit_test\Debug\unit_test.exp

**Comment by greg7mdp** [comment]
Thanks for the report @fabioparodi . Does it help if you define the preprocessor variable `__cpp_inline_variables`?

**Comment by fabioparodi** [comment]
Thanks for answering Gregory

It looks like __cpp_inline_variables is predefined by the compiler

#define __cpp_inline_variables

Makes:

error C2220: warning treated as error - no 'object' file generated
warning C4117: macro name '__cpp_inline_variables' is reserved, '#define' ignored

I’ve noticed that the problem happens when I include btree.h from two different source files.

Fabio

Da: Gregory Popovitch ***@***.***>
Risposta: greg7mdp/parallel-hashmap ***@***.***>
Data: mercoledì 21 aprile 2021 19:35
A: greg7mdp/parallel-hashmap ***@***.***>
Cc: Fabio Parodi ***@***.***>, Mention ***@***.***>
Oggetto: Re: [greg7mdp/parallel-hashmap] compiler errors with msvc (#89)


Thanks for the report @fabioparodi<https://github.com/fabioparodi> . Does it help if you define the preprocessor variable __cpp_inline_variables?

**Comment by greg7mdp** [comment]
Oh I see!
I did try including btree.h in two separate source file with my current compiler (16.9.2) and it builds fine.
Can you try replacing line 251:

```#ifdef __cpp_inline_variables```

with:

```#if defined(__cpp_inline_variables) && !defined(_MSC_VER)```

**Comment by fabioparodi** [comment]
Thanks Gregory with the change at line 251 it works
With best regards
fabio

Da: Gregory Popovitch ***@***.***>
Risposta: greg7mdp/parallel-hashmap ***@***.***>
Data: mercoledì 21 aprile 2021 20:41
A: greg7mdp/parallel-hashmap ***@***.***>
Cc: Fabio Parodi ***@***.***>, Mention ***@***.***>
Oggetto: Re: [greg7mdp/parallel-hashmap] compiler errors with msvc (#89)


Oh I see!
I did try including btree.h in two separate source file with my current compiler (16.9.2) and it builds fine.
Can you try replacing line 251:

#ifdef __cpp_inline_variables

with:

#if defined(__cpp_inline_variables) && !defined(_MSC_VER)

**Comment by greg7mdp** [comment]
Thanks @fabioparodi I checked in the change
