### ISSUE TITLE
Tagged release and questions about long term support

### ISSUE THREAD

**Issue by jmbnyc** [greg7mdp/parallel-hashmap#90]
Greg,
There have been a large number of commits since your last tag. Is it safe to use the "head" of the master branch or is there a reason why that there is not a more recent tag? Can you also comment on "long term" support that you plan for this code? e.g. do you plan to keep it up to date if there are bugs that arise?

**Comment by greg7mdp** [comment]
Hi @jmbnyc,

Yes, it is safe to use the head of the master branch. But I will also tag a new release.
I do plan to keep the code up to date if bugs arise.

**Comment by greg7mdp** [comment]
added new tagges release 1.33.
