### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [greg7mdp/parallel-hashmap#91]
How to build the documentation on linux?
`cd html && make all` doesn't work fo me:
```
stack exec ghc -- -o includes.exe -no-keep-hi-files -no-keep-o-files includes.hs
make: stack: No such file or directory
make: *** [Makefile:30: includes.exe] Error 127
```

**Comment by greg7mdp** [comment]
Hi @Alessandro-Barbieri 

I'm sorry, this is not really maintained, I just built that a long time ago when I first worked on phmap. What it builds is the page from https://greg7mdp.github.io/parallel-hashmap/. I just added the source to the repository but I didn't intend for users to rebuild the doc.

I'm not sure if the doc would still build with the current version of haskell and pandoc, and I'm not planning to look into this.
