### ISSUE TITLE
Exception during emplace

### ISSUE THREAD

**Issue by jmbnyc** [greg7mdp/parallel-hashmap#92]
Greg,

In the following function:

    template <class... Args>
    void emplace_at(size_t i, Args&&... args) {
        PolicyTraits::construct(&alloc_ref(), slots_ + i,
                                std::forward<Args>(args)...);

        assert(PolicyTraits::apply(FindElement{*this}, *iterator_at(i)) ==
               iterator_at(i) &&
               "constructed value does not match the lookup key");
    }

Why would this assert?

This happens for me when I try to insert strings into a flat_set where the strings are "XX", "X" and "". All strings hash to different values so I am not sure why it asserts.

**Comment by jmbnyc** [comment]
Greg,
I think I figured it out so never mind - I had an issue with my is_equal function that was not dealing with left and right side both being strings of 0 length.

**Comment by greg7mdp** [comment]
Sounds good, thanks for letting me know @jmbnyc, closing the issue.

**Comment by jmbnyc** [comment]
Actually, sorry to be a nuisance. Can you explain why you have that assertion? I have a situation where I am inserting a "Value" into the set where the Value can be various types, unsigned long, long, double, null, string, bool etc but there the equivalent rules are tricky wrt NULL comparison. A string of zero length is considered NULL so in a weird way comparison against null always return false. If I remove that assert then everything works as I expect but with the assert it asserts. Thus, I would like to know why you think that is an assertable condition.

**Comment by greg7mdp** [comment]
Well, the idea is that when you insert a value into a hash map, and then do a `find()`, you should find the value you just inserted. If not I don't see how it could possibly make sense.

**Comment by jmbnyc** [comment]
In my example I have a "set" where I insert "X", "XX" and "". If I then try to "find" "" it works just fine but all because of my Value object knows how to do the right thing. For some reason, that assert blows when I insert "". If I remove, then insert "" works and then a subsequent find against Null or zero length string works as expected.

**Comment by greg7mdp** [comment]
Can you provide an example I can run, so I can look into it?

**Comment by jmbnyc** [comment]
Greg,
You are correct, it does not add, I added my own check after the insert. However, I now see why the code in question works (this is part of a larger "in" expression evaluator. 
I can explain but it would waste your time. For my purposes, I need to remove the ASSERT or avoid inserting 0 length strings (which is the route I will look to take). Again, sorry to bother you but this "Value" equality thing is rather complex when dealing with Nulls. I see now that we have a function in front of the "in" check that handles nulls so they are never looked up in the set, e.g. no reason to add them.

**Comment by greg7mdp** [comment]
Jeffrey, I'd rather keep the assert as I believe it is a useful warning that you are inserting into the set a value that you cannot find. I think in your case it would be preferable to not insert them also. Also because they are not found you could possibly insert this value many times, filling your set with inaccessible values.

**Comment by jmbnyc** [comment]
Agreed. Let me do that and see if the regression test passes. This regression test was bombing when I changed from robin_hood map to your implementation: I changed because robin_hood has overflow issues that are unacceptable.

**Comment by jmbnyc** [comment]
Quick update: yeah, that seems to make everything happy so I'll leave the assert and just not insert 0 length strings.

**Comment by greg7mdp** [comment]
Great, glad it works out well for you.
