### ISSUE TITLE
Allocator deprecation warnings when compiled with C++17

### ISSUE THREAD

**Issue by Ravbug** [greg7mdp/parallel-hashmap#94]
Apple Clang 12.0.5 C++17 raises deprecation warnings:

```cpp
phmap_base.h 1306: 'rebind<M>' is deprecated
phmap_base.h 1530: 'construct' is deprecated
phmap_base.h 1541: 'destroy' is deprecated
```
These functions were deprecated in C++17: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r0.html#2.4

**Comment by greg7mdp** [comment]
Thanks for reporting the issue @Ravbug , should be fixed with my last checkin.
