### ISSUE TITLE
minor memory leakage with msvc

### ISSUE THREAD

**Issue by fabioparodi** [greg7mdp/parallel-hashmap#99]
Visual Studio Version 16.9.5 is detecting a few memory leaks when the program terminates.
They are all 8 bytes long and started to appear when I converted std::set and std::map to use the phmap versions.
The number of leaks does not increase with time/usage; I have the impression that they are related to singleton objects. Not a big concern, however, it would be better to fix it. Any ideas? I can contribute with testing/debugging, but would like to get some directions.

MSVC debugger output:

```
Detected memory leaks!
Dumping objects ->
{5865474} normal block at 0x0B171B28, 8 bytes long.
 Data: <(       > 28 1B 17 0B 00 00 00 01 
{2209072} normal block at 0x0B1627E8, 8 bytes long.
 Data: < '      > E8 27 16 0B 00 00 00 01 
{1430683} normal block at 0x0B5CC588, 8 bytes long.
 Data: <  \     > 88 C5 5C 0B 00 00 00 01 
{1126096} normal block at 0x086A2848, 8 bytes long.
 Data: <H(j     > 48 28 6A 08 00 00 00 01 
{989} normal block at 0x01C27CB8, 8 bytes long.
 Data: < |      > B8 7C C2 01 00 00 00 01 
{606} normal block at 0x01C19D80, 8 bytes long.
 Data: <        > 80 9D C1 01 00 00 00 01 
{579} normal block at 0x01C0A690, 8 bytes long.
 Data: <        > 90 A6 C0 01 00 00 00 01 
Object dump complete.
```

**Comment by greg7mdp** [comment]
Hi @fabioparodi , which classes exactly do you use from phmap?

**Comment by fabioparodi** [comment]
Thanks for answering Greg

I am using:
node_hash_set, flat_hash_map, priv, flat_hash_set, parallel_node_hash_set, parallel_node_hash_map, node_hash_map, parallel_flat_hash_set, btree_map, parallel_flat_hash_map, btree_set

Fabio

Da: Gregory Popovitch ***@***.***>
Risposta: greg7mdp/parallel-hashmap ***@***.***>
Data: martedì 18 maggio 2021 19:52
A: greg7mdp/parallel-hashmap ***@***.***>
Cc: Fabio Parodi ***@***.***>, Mention ***@***.***>
Oggetto: Re: [greg7mdp/parallel-hashmap] minor memory leakage with msvc (#99)


Hi @fabioparodi<https://github.com/fabioparodi> , which classes exactly do you use from phmap?

**Comment by greg7mdp** [comment]
Hi @fabioparodi , can you try the new version of btree.h to see if it fixes the issue?

**Comment by fabioparodi** [comment]
Hello Gregory
The new version of btree.h fixes the leak. It was the empty node.
Thanks
Fabio

Da: Gregory Popovitch ***@***.***>
Risposta: greg7mdp/parallel-hashmap ***@***.***>
Data: mercoledì 19 maggio 2021 14:07
A: greg7mdp/parallel-hashmap ***@***.***>
Cc: Fabio Parodi ***@***.***>, Mention ***@***.***>
Oggetto: Re: [greg7mdp/parallel-hashmap] minor memory leakage with msvc (#99)


Hi @fabioparodi<https://github.com/fabioparodi> , can you try the new version of btree.h to see if it fixes the issue?

**Comment by greg7mdp** [comment]
Great, thanks for the update @fabioparodi (and also for reporting the issue).
